- index.js
So per the example at https://github.com/dherault/serverless-offline#credits-and-inspiration, instead of building up that params object, how about having the requestTemplates applied to the event?  That would make it feel a little more like it's really running in an API Gateway -> Lambda setup.  This has made some of my testing much easier, and kept the local-runner-magic concerns out of handler code.
> Apply request templates to an event

- README.md
- index.js
Added optional '-s <pathname>' for local hosting for https. 
Pathname points to where the cert.pem and key.pem should be located.
Readme also updated
> Added https with -s

- src/index.js
The `node4.3` runtime already in the serverless `master` - https://github.com/serverless/serverless/commit/08952ee36a3335c67c992e65a39c2e87a6c2a485
P.S. Thanks for the great plugin, it's really awesome!
> Adds `node4.3` runtime

- src/createVelocityContext.js
API Gateway added this method a month ago to the $util object in mapping templates.
> Added support for parseJson in $util object

- README.md
- package.json
- src/createAuthScheme.js
- src/functionHelper.js
- src/index.js
I've started adding support for Authorization functions #41. Hopefully I am on the right track with this.
I'll comment when it's ready for a review
> WIP - Authorization Function Support

- README.md
- src/createAuthScheme.js
- src/functionHelper.js
- src/index.js
Support promises in auth function, different auth headers, and pass whole header to event object. #41 
P.S. Sorry about not linting last time. I've tried to do that this time.
> Fixes for #41

- src/createAuthScheme.js
- src/index.js
- src/resetEnvVariables.js
- src/utils.js
Not sure if I should/how to clear old env variables before calling authorization handler.
> Fixes for #41. Set env variables before calling authorization handler.

- next_version/src/createApigContext.js
- src/createVelocityContext.js
Set the `principalId` from the request authorizer on the lambda context.
> set principalId on contexts

- .eslintrc.js
- README.md
- package.json
- src/Endpoint.js
- src/createAuthScheme.js
- src/createVelocityContext.js
- src/debugLog.js
- src/functionHelper.js
- src/index.js
- src/javaHelper.js
- src/offline-default.req.vm
- src/offline-default.res.vm
- src/offline-endpoint.json
- src/renderVelocityTemplateObject.js
- src/resetEnvVariables.js
- src/sample-vm-request-template.req.vm
- src/utils.js
This branch migrates this plugin to be compatible with the new v1 serverless plugin syntax.
The commits should hopefully be granular enough to follow. I tested with serverless@1.0.0-beta.2 with success.
Let me know if there are any issues.
> serverless v1.0.x compatibility

- src/index.js
Support stage variables
Ex = sls offline --stage offline
[serverless.yml]
custom:
stageVariables:
myStageVariable: ${opt:stage, self:provider.stage}
> Support stage variables from serverless-plugin-stage-variables

- package.json
- src/index.js
Thanks for the great plugin! 
I had a need for running the plugin inside a unit test and wanted to synchronise with the server listen. I also noticed that the internal `serverless` plugin hooks return a promise so followed that pattern. Would like to add some tests but a bit busy at the moment - might come back to it later :)
> Promisified the start hook

- src/index.js
> Handle Simple http setup, ex. - http: GET users/index

- src/index.js
- test/integration/offline.js
I'll be refactoring the integration tests in this branch, trying to contextualize them to keep them in order.
I'll be reintegrating the branch with master every few days so other contributors have them already sorted.
> Contextualizing tests

- .travis.yml
Added simple travis ci yml, to have basic automatic Unit Testing.
The rest of the configuration needs to be done by an owner of the repo. The configuration is pretty straightforward. Refer [Here](https://docs.travis-ci.com/user/getting-started/)
If there is something else to add. Let me know.
> Add Travis Config

- src/index.js
- test/integration/offline.js
Fixes for issue #179 
Just a variable fix and a companion unit test. 
Cheers
> Trailing slash

- package.json
- src/createLambdaProxyContext.js
- test/integration/offline.js
This is a minor update to support custom content types without any backwards compatibility breaks.
> Updated lambda proxy to support custom content types - including tests.

- src/createLambdaProxyContext.js
Hi guys,
This is a small fix about data received when you usa lambda proxy. Fixes #213
> Fix on body to be equal on Serverless in AWS Lambda

- src/index.js
> Add default identitySource when authorizer is an object

- src/createLambdaProxyContext.js
- src/index.js
@dherault - not sure how to add more tests. Thoughts?
I think this fixes #173 as well.
> app - preventing hapi from parsing payloads; resolves #177.

- src/index.js
> fix setting default for identitySource

- src/index.js
This avoids functions overriding other functions envs
sample project here that demonstrates the bug
https://gist.github.com/guillaume/9b4e252f75fe3fa0c7eb9d570bf0c259
without the patch it prints
```
$ sh test.sh
"baz""baz""baz"
```
with the patch it prints
```
$ sh test.sh
"foo""bar""baz"
```
> Assign process.env per function calls. 

- manual_test/serverless.yml
- package.json
- src/index.js
updates protectedRoutes logic to include request method, in addition to the request path
fixes #268
> updates protectedRoutes logic to include request method

- README.md
- src/index.js
Allows to locally test lambdas referencing ARN Authorizer 
Support Non-Local Custom Authorisers  #118
> Added --noAuth CLI option to disable Authorizer

- src/index.js
ref https://github.com/dherault/serverless-offline/issues/357
> * handle base64 encoded binary response from aws lambda function

- package.json
Add name to contributors based on commit bf8af6282de55aec1628877eec60edacb3729277
> Add name to contributors 

- package.json
- src/createLambdaProxyContext.js
- test/unit/createLambdaProxyContextTest.js
Hopefully the first of many contributions :) Fixes concerns from https://github.com/dherault/serverless-offline/pull/292
https://github.com/dherault/serverless-offline/pull/319 didn't seem to go anywhere, this PR is solving the same issue
> Fix for lower cased Authorization header not being catered for

- src/index.js
AWS released support for Node 8.10 today.
Fixes https://github.com/dherault/serverless-offline/issues/381
> Add support for nodejs8.10

- README.md
As commented in #195 we should reflect that AWS profile can only be changed by env variable right now.
> Update README with info for changing AWS profile

- src/authMatchPolicyResource.js
Fixes https://github.com/dherault/serverless-offline/issues/387
> Fixes the case when policy === *

- README.md
- src/index.js
Add the option to preserve trailing slashes on the incoming request path.
> Option to preserve trailing slash

- src/index.js
- test/integration/offline.js
This PR is addressing https://github.com/dherault/serverless-offline/issues/204. 
This is far from ideal solution and is based on the assumption that it is better the offline support to work with limitation rather than failing to start.
> skip HEAD routes to avoid HAPI error

- src/authCanExecuteResource.js
- test/unit/authCanExecuteResourceTest.js
IAM statement effect is actually case-insensitive, so have refactored to do a case-insensitive comparison
> Fix Allow statement case sensitivity

- src/index.js
Set process.env in shell script,  #259
> Pass provider environment to shell

- test/unit/createLambdaProxyContextTest.js
add failing unittest. see https://github.com/dherault/serverless-offline/pull/411
> add failing unittest

- src/createAuthScheme.js
> Add support for async authorizers

- src/index.js
- test/unit/authCanExecuteResourceTest.js
- test/unit/createLambdaProxyContextTest.js
Fix all the eslint issues.
Most importantly fix an issue on #421 where the right message was created but not used 🤦‍♂️ 
It would be great to have travis ci or similar automatically running the linting and the tests.
I'd be happy to set it up but access to the repo is needed 🙂
> Fix eslint issues

- package.json
Just realized that you list all contributors in package.json.
Adding myself 🙂
> Add myself to contributors

- src/index.js
Fixes the regression introduced in #437 and closes #445.
> Fix server startup issue

- src/index.js
- test/integration/offline.js
> use h.state for set-cookie headers

- package.json
- src/createAuthScheme.js
- src/createLambdaProxyContext.js
- src/index.js
- test/support/RequestBuilder.js
- test/unit/createLambdaProxyContextTest.js
issue #510 
added multiValueHeader and multiValueQueryStringParameter support to the authorizer event, and added multiValueHeader support to the request and response.
> add multiValue header and query params to authorizer event and response

- src/createAuthScheme.js
- src/index.js
Support for identityValidationExpression, custom authorization header
> identityValidationExpression support

- src/functionHelper.js
> Support runtime override for individual functions

- src/createLambdaProxyContext.js
Fixes https://github.com/dherault/serverless-offline/issues/610
> Only assign a length if its a valid body

- src/authMatchPolicyResource.js
- test/unit/authMatchPolicyResourceTest.js
Add test and support for single character wildcard #613 
Refactor resource path - resource policy path test to use regular expression
> Single character wildcard

- src/authCanExecuteResource.js
- test/unit/authCanExecuteResourceTest.js
Implement check for explicit deny statement
Closes #340
> Deny statements

- package-lock.json
- src/createAuthScheme.js
- src/createLambdaContext.js
- src/index.js
I noticed that serverless-offline was not respecting the default timeout that I set in the `provider` field. These changes fixed it for me.
> Fallback to timeout and memorySize from provider

- src/functionHelper.js
- src/index.js
Reverts dherault/serverless-offline#640
> Revert "fixes memory leak"

- src/createAuthScheme.js
- src/createLambdaProxyContext.js
- test/unit/createLambdaProxyContextTest.js
> #638 Fix for encoding, aws looks to not do encoding anymore

- package-lock.json
- package.json
- src/jsonPath.js
* jsonpath-plus 0.16.0 -> 0.19.0
* trim-newlines 2.0.0 -> 3.0.0
* added npm-check for ease of listing of packages that are out of date
> Packages Upgrade

- test/integration/offline.js
based on `Promise tests`, not taking https://github.com/dherault/serverless-offline/issues/678 into account. will have a look later ...
> Add tests for handlers using async functions

- package.json
added **files** to package.json.
@dherault  not sure how your deployment script looks like, but currently it uploads (and installs) some unneeded files to npm: `manual_test_websocket` folder and the `.eslintrc.js.`
also added some additional keywords.
> package.json files

- src/ApiGateway.js
> Avoid setting empty response headers for v5

- src/api-gateway/ApiGateway.js
> Avoid setting empty response headers for v6

- src/ServerlessOffline.js
> check for http event with private: true

- src/events/http/Endpoint.js
- src/events/http/HttpServer.js
#848
ref: https://github.com/serverless/serverless/blob/v1.59.2/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js#L380-L416
> Support integration types aws-proxy, aws_proxy, and aws

- package-lock.json
Hi, I thought I'd leave this here.
I was able to fix `npm audit` found vulnerabilities w/ `npm audit fix`
> [fix] 66 hapi-related vulnerabilities detected by npm audit

- src/lambda/handler-runner/docker-runner/DockerContainer.js
https://github.com/dherault/serverless-offline/issues/768#issuecomment-579989200, https://github.com/dherault/serverless-offline/issues/768#issuecomment-582220885
Docker for mac 2.2.0.0 probably takes time to establish connection with container.
It can be resolved by waiting it to use `ping` API of `lambci/lambda`.
https://github.com/lambci/docker-lambda/blob/b8c8759ddb90688d4aabc37800c2c7221fe4c478/provided/run/init.go#L441-L443
> Fix connection refused error on mac

- src/ServerlessOffline.js
Resolves #913
---
Tested manually with a local serverless project. Not sure if I need to add/update any tests.
> "offline:ready" hook

- package-lock.json
- package.json
- src/lambda/LambdaFunction.js
- src/lambda/handler-runner/docker-runner/DockerRunner.js
- tests/integration/_testHelpers/compressArtifact.js
- tests/integration/_testHelpers/index.js
- tests/integration/artifact/local/.gitignore
- tests/integration/artifact/local/handler1.js
- tests/integration/artifact/local/handler2.js
- tests/integration/artifact/local/localArtifact.test.js
- tests/integration/artifact/local/serverless.yml
- tests/integration/docker/artifact/.gitignore
- tests/integration/docker/artifact/artifact.test.js
- tests/integration/docker/artifact/handler.js
- tests/integration/docker/artifact/serverless.yml
This PR will add local artifact support to all handler runner.
https://serverless.com/framework/docs/providers/aws/guide/packaging#artifact
It probably allows to docker runner to support Java and .NET runtimes (#876, #895).
> Support local artifact

- src/ServerlessOffline.js
Fixes https://github.com/dherault/serverless-offline/issues/939
> Fix for attempt to process undefined events property

- src/lambda/handler-runner/child-process-runner/ChildProcessRunner.js
Allows for console.* functions to display
>  #942 Fix for child process sharing the stdio of parent

- package.json
- src/lambda/HttpServer.js
- src/lambda/routes/invocations/invocationsRoute.js
- src/lambda/routes/invoke-async/invokeAsyncRoute.js
> ISSUE-947 cors options are ignored for the lambda server

- src/lambda/LambdaFunction.js
> Add IS_OFFLINE env var to all handler runners

- src/events/http/HttpServer.js
Just a tiny change to fix the reference to the schema when we want to log it.
> Fix schema logging

- .github/PULL_REQUEST_TEMPLATE.md
- .travis.yml
- change node 13 to 14 (LTS version) for CI testing; current latest/stable release and will most likely be added to the aws lambda environment soon (ref: https://github.com/nodejs/Release#nodejs-release-working-group)
- add pull request template to add a little structure when submitting PRs
> chore: add PR template and change node 13 to 14 for tests

- package.json
- tests/integration/groovy/groovy.test.js
- tests/integration/kotlin/kotlin.test.js
> Release 7.1.0

- src/events/schedule/Schedule.js
Adds support for arrays of `rate` configuration on `schedule` items. The type is checked and converting from string to array if necessary to continue to support versions of Serverless older than v2.58.0.
[Serverless v2.58.0](https://github.com/serverless/serverless/releases/tag/v2.58.0) adds support to [Specify multiple schedule expressions](https://www.serverless.com/framework/docs/providers/aws/events/schedule/#specify-multiple-schedule-expressions). This behavior changes the `rate` configuration from a string to array.
Fixes #1275.
Manually using the example configuration from #1275. I found no existing tests for schedule events so I did not add any new ones. I'm willing to spend some time to figure out how to add baseline tests for this if that would be desirable (but was slightly …
> fix: Ensure support for array-based schedule event rates

- src/lambda/handler-runner/docker-runner/DockerContainer.js
It appears some progress logs were not conditioned properly
Fixes #1303
> Fix handling of modern logs

- .github/workflows/integrate.yml
- tests/integration/artifact/local/handler1.js
Debugging failing tests on master branch
> Enforce printing output for debugging failed tests on master

- README.md
Changed the "thorough" typo to "throughout".
Noticed it while reading through the docs, though I would submit a quick PR to fix it.
N/A
N/A
> fix minor typo in docs

- src/events/http/Endpoint.js
- src/events/http/HttpServer.js
- src/events/http/lambda-events/LambdaProxyIntegrationEvent.js
- tests/old-unit/LambdaProxyIntegrationEvent.test.js
- tests/old-unit/offline.test.js
Reverts dherault/serverless-offline#1247
> Revert "Fix lambda async behaviour"

- src/events/http/HttpServer.js
- src/events/http/lambda-events/LambdaProxyIntegrationEvent.js
- src/events/http/lambda-events/LambdaProxyIntegrationEventV2.js
Reverts dherault/serverless-offline#1265
> Revert "Fixed the problem that the binary is not uploaded normally."

- src/lambda/handler-runner/python-runner/PythonRunner.js
- src/lambda/handler-runner/python-runner/invoke.py
- src/lambda/routes/invocations/InvocationsController.js
- tests/integration/python/python2/handler.py
- tests/integration/python/python2/python2.test.js
- tests/integration/python/python2/serverless.yml
- tests/integration/python/python3/handler.py
- tests/integration/python/python3/python3.test.js
- tests/integration/python/python3/serverless.yml
Reverts dherault/serverless-offline#1365
> Revert "fixed hanging when python raises exception or return nothing"

- .github/workflows/integrate.yml
- .github/workflows/validate.yml
> ci: bump github actions

- .eslintrc.js
- package-lock.json
- package.json
> fix: remove babel-eslint

- .gitignore
- prettier.config.js
> chore: remove prettier default, add test folder to gitignore

- src/lambda/handler-runner/go-runner/GoRunner.js
When launching Go's lambda, use `go build` command instead of `go run` command to run the binary file.
I was looking for a way other than using `--useDocker` before and came up with the following issue.
https://github.com/dherault/serverless-offline/issues/1334
Also, I found and commented on pull requests to add the feature to do local launches without `--useDocker`
https://github.com/dherault/serverless-offline/pull/1320#issuecomment-1060126382
`go build` command alows you to import and use all packages including main, so you can use not only a single main.go, but also separate packages.
> feat: Use `go build` command instead of `go run` command

- README.md
> doc: remove worker thread version requirement

- package-lock.json
- package.json
> doc: remove unused dependency

- package-lock.json
- package.json
This reverts commit d3ae107af8f73138d8276e929323436d957ab930.
> Revert "chore: bump deps"

- package-lock.json
- package.json
- src/lambda/handler-runner/python-runner/PythonRunner.js
> refactor: remove extend module, replace with Object.assign

- babel.config.js
- package-lock.json
- package.json
> build: use @babel/preset-env

- src/ServerlessOffline.js
- src/events/http/Endpoint.js
- src/events/http/HttpServer.js
- src/events/http/lambda-events/LambdaProxyIntegrationEventV2.js
- src/events/schedule/Schedule.js
- src/events/websocket/WebSocketClients.js
- src/lambda/LambdaFunction.js
- src/lambda/LambdaFunctionPool.js
- src/lambda/handler-runner/HandlerRunner.js
- src/lambda/handler-runner/docker-runner/DockerContainer.js
- src/lambda/handler-runner/docker-runner/DockerImage.js
- src/lambda/handler-runner/go-runner/GoRunner.js
- src/lambda/handler-runner/in-process-runner/InProcessRunner.js
- src/lambda/handler-runner/java-runner/JavaRunner.js
- src/lambda/handler-runner/python-runner/PythonRunner.js
- src/lambda/handler-runner/ruby-runner/RubyRunner.js
- src/lambda/handler-runner/worker-thread-runner/WorkerThreadRunner.js
> refactor: use private methods

- .github/workflows/integrate.yml
- .github/workflows/validate.yml
- package.json
- tests/scenario/docker-serverless-webpack-test/docker-serverless-webpack.test.js
- tests/scenario/serverless-webpack-test/serverless-webpack.test.js
> ci!: remove node.js v12 support, add v18

- tests/scenario/docker-serverless-webpack-test/docker-serverless-webpack.test.js
- tests/scenario/docker-serverless-webpack-test/package-lock.json
- tests/scenario/docker-serverless-webpack-test/package.json
- tests/scenario/serverless-webpack-test/package-lock.json
- tests/scenario/serverless-webpack-test/package.json
- tests/scenario/serverless-webpack-test/serverless-webpack.test.js
> test: fix failing tests on node.js v18

- tests/scenario/apollo-server-lambda/package-lock.json
- tests/scenario/apollo-server-lambda/package.json
- tests/scenario/docker-in-docker/package-lock.json
- tests/scenario/docker-in-docker/package.json
- tests/scenario/serverless-plugin-typescript-test/package-lock.json
- tests/scenario/serverless-plugin-typescript-test/package.json
> test: bump scenario test deps

- tests/scenario/apollo-server-lambda/package-lock.json
- tests/scenario/apollo-server-lambda/package.json
> chore: bump apollo server lambda scenario deps

- src/lambda/LambdaFunction.js
- src/lambda/handler-runner/docker-runner/DockerContainer.js
- src/lambda/handler-runner/go-runner/GoRunner.js
> refactor!: use fs/promises

- tests/integration/go/go1.x/go1.x.test.js
- tests/integration/python/python-big-json/python-big-json.test.js
- tests/integration/python/python3/python3.test.js
> test: revert go/python detection

- package-lock.json
- package.json
- src/events/websocket/WebSocketClients.js
- tests/integration/_testHelpers/websocketPromise.js
- tests/integration/websocket-twoway/websocket-twoway.test.js
> chore: bump ws v8+, lint-staged v12+

- .husky/pre-commit
- .lintstagedrc
- package-lock.json
- package.json
> chore: bump husky

- .husky/pre-commit
- package-lock.json
- package.json
> chore: bump @hapi/boom

- package-lock.json
- package.json
- src/lambda/LambdaFunction.js
> refactor: use object.entries

- babel.config.js
> build: set babel target to node.js v14.18

- src/events/http/lambda-events/LambdaProxyIntegrationEventV2.js
- src/lambda/handler-runner/docker-runner/DockerContainer.js
- src/lambda/handler-runner/in-process-runner/InProcessRunner.js
- src/lambda/handler-runner/in-process-runner/clearModule.js
- tests/integration/_testHelpers/compressArtifact.js
- tests/integration/_testHelpers/setupTeardown.js
> fix: cleanup

- .eslintrc.cjs
- src/lambda/handler-runner/in-process-runner/InProcessRunner.js
- src/lambda/handler-runner/in-process-runner/clearModule.js
> refactor: use async fs/promises

- README.md
Changed 'wheter' to 'whether'
Fixing a typo in docs
No tests required
> doc: fix a typo in README

- CONTRIBUTING.md
> doc: fix CONTRIBUTING.md for v9

- src/lambda/handler-runner/docker-runner/DockerContainer.js
> refactor: use async unlink

- tests/integration/docker/provided/dockerProvided.test.js
> test: fix docker provided tests

- tests/integration/docker/multiple/dockerMultiple.test.js
- tests/integration/docker/multiple/handler.js
- tests/integration/docker/multiple/serverless.yml
> test: fix docker multiple tests

- tests/integration/docker/artifact/artifact.test.js
> test: fix docker artifact tests

- tests/integration/docker/access-host/accessHost.test.js
- tests/integration/docker/access-host/serverless.yml
- tests/integration/docker/access-host/src/package-lock.json
- tests/integration/docker/access-host/src/package.json
- tests/mochaHooks.cjs
> test: fix docker access host tests

- tests/scenario/docker-serverless-webpack.test.js
> test: fix docker serverless webpack tests

- .github/workflows/integrate.yml
- .github/workflows/validate.yml
- tests/integration/ruby/ruby.test.js
> test: fix ruby tests

- .github/workflows/integrate.yml
- .github/workflows/validate.yml
- tests/integration/go/go1.x/go1.x.test.js
- tests/integration/go/go1.x/serverless.yml
> test: fix go tests

- .github/workflows/integrate.yml
- .github/workflows/validate.yml
- tests/integration/groovy/groovy.test.js
- tests/integration/java/java.test.js
- tests/integration/kotlin/kotlin.test.js
- tests/integration/scala/scala.test.js
> test: fix java/kotlin/groovy/scala tests

- .github/workflows/integrate.yml
- tests/integration/python/python-big-json/python-big-json.test.js
- tests/integration/python/python-module/python-module.test.js
- tests/integration/python/python3/python3.test.js
> test: fix python tests

- tests/integration/docker/go/go1.x/dockerGo1.x.test.js
- tests/integration/docker/go/go1.x/serverless.yml
> test: fix docker go tests

- tests/integration/docker/layers/dockerLayers.test.js
- tests/integration/docker/layers/serverless.yml
> test: fix docker layers tests

- src/ServerlessOffline.js
- src/events/http/HttpServer.js
fixes https://github.com/dherault/serverless-offline/issues/1466
> fix: remove NODE_ENV=test condition

- tests/scenario/docker-in-docker.test.js
- tests/scenario/docker-in-docker/docker-compose.yml
- tests/scenario/docker-in-docker/entrypoint.sh
- tests/scenario/docker-in-docker/handler.js
- tests/scenario/docker-in-docker/package-lock.json
- tests/scenario/docker-in-docker/package.json
- tests/scenario/docker-in-docker/serverless.yml
> test: fix docker-in-docker tests

- tests/integration/_testHelpers/setupTeardown.js
- tests/integration/websocket-authorizer/websocket-authorizer.test.js
- tests/integration/websocket-oneway/websocket-oneway.test.js
- tests/integration/websocket-twoway/websocket-twoway.test.js
> test: re-activate websocket tests, add temp workaround

- README.md
- src/config/commandOptions.js
- src/config/defaultOptions.js
- src/lambda/LambdaFunction.js
- tests/lambda-run-mode/worker-threads/local-env-vars/serverless.yml
- tests/lambda-run-mode/worker-threads/local-env-vars/src/handler.js
- tests/lambda-run-mode/worker-threads/local-env-vars/src/package.json
- tests/lambda-run-mode/worker-threads/local-env-vars/worker-threads-local-env-vars.test.js
> feat: add local environment variables flag

- src/lambda/handler-runner/go-runner/GoRunner.js
> refactor: replace execaSync with execa (promise)

- src/events/http/HttpServer.js
fixes: https://github.com/dherault/serverless-offline/issues/1528
> fix: tls options

- src/ServerlessOffline.js
> fix: region + stage startup log

- .npmignore
- package.json
> fix: published package content

- src/ServerlessOffline.js
> fix: deprecate use child processes

- src/lambda/LambdaFunction.js
- tests/integration/docker/access-host/serverless.yml
- tests/integration/docker/artifact/serverless.yml
- tests/integration/docker/go/go1.x/serverless.yml
- tests/integration/docker/layers/serverless.yml
- tests/integration/docker/multiple/serverless.yml
- tests/integration/docker/nodejs/nodejs12.x/serverless.yml
- tests/integration/docker/provided/serverless.yml
- tests/integration/docker/python/python3.6/serverless.yml
- tests/integration/docker/python/python3.7/serverless.yml
- tests/integration/docker/python/python3.8/serverless.yml
- tests/integration/docker/ruby/ruby2.7/serverless.yml
- tests/lambda-run-mode/worker-threads/instances/worker-threads-instances.test.js
- tests/lambda-run-mode/worker-threads/timeout/worker-threads-timeout.test.js
- tests/runtimes/go/aws-golang-simple-http-endpoint/serverless.yml
- tests/runtimes/go/go1.x/serverless.yml
- tests/scenario/docker/docker-serverless-webpack/app/serverless.yml
> feat: add timeout feature, hookup noTimeout option

- package-lock.json
- package.json
> fix: pin luxon to v3.0.1

- package.json
> feat: add Lambda class to package exports

- .github/workflows/integrate.yml
- .github/workflows/validate.yml
- tests/lambda-run-mode/worker-threads/timeout/worker-threads-timeout.test.js
- tests/runtimes/python/python-big-json/python-big-json.test.js
- tests/runtimes/python/python-module/python-module.test.js
- tests/runtimes/python/python3/python3.test.js
> ci: add macos

- .github/workflows/nodejs.yml
> ci: setup python

- README.md
- src/ServerlessOffline.js
- src/config/commandOptions.js
- src/config/defaultOptions.js
> feat: deprecate api keys option

- README.md
- src/ServerlessOffline.js
- src/config/commandOptions.js
- src/config/defaultOptions.js
BREAKING, next major release, v11
> fix!: remove disableScheduledEvents option

- src/events/http/HttpServer.js
- tests/_testHelpers/setupTeardown.js
- tests/events/http/private/generated-api-key/generated-api-key.test.js
- tests/events/http/private/generated-api-key/serverless.yml
- tests/events/http/private/generated-api-key/src/index.js
- tests/events/http/private/generated-api-key/src/package.json
> test: add test for generated api key

- src/errors/LambdaTimeoutError.js
- src/errors/index.js
- src/lambda/LambdaFunction.js
> fix: timeout terminating process

- tests/scenario/lambda-frameworks/middy-lambda/app/.npmrc
- tests/scenario/lambda-frameworks/middy-lambda/app/package-lock.json
- tests/scenario/lambda-frameworks/middy-lambda/app/package.json
- tests/scenario/lambda-frameworks/middy-lambda/app/serverless.yml
- tests/scenario/lambda-frameworks/middy-lambda/app/src/index.js
- tests/scenario/lambda-frameworks/middy-lambda/middy-lambda.test.js
> test: add scenario test for middy, issue #1595

- tests/scenario/lambda-frameworks/apollo-federation-supergraph/apollo-federation-supergraph.test.js
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/.npmrc
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/gateway/schema/supergraph-gateway.graphql
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/gateway/src/index.js
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/inventory/schema/inventory.graphql
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/inventory/src/data.js
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/inventory/src/index.js
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/inventory/src/resolvers.js
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/package-lock.json
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/package.json
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/products/schema/products.graphql
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/products/src/data.js
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/products/src/index.js
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/products/src/resolvers.js
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/serverless.yml
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/users/schema/users.graphql
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/users/src/data.js
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/users/src/index.js
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/users/src/resolvers.js
> test: add apollo federation scenario test

- src/lambda/handler-runner/HandlerRunner.js
> fix: logging for unhandled exceptions in handler

- src/events/http/HttpServer.js
- src/events/websocket/HttpServer.js
- tests/endToEnd/optionParameters/optionParameters.test.js
- tests/endToEnd/optionParameters/src/serverless.yml
> fix: path access with trailing slash

- examples/lambda-invoke-v3/.npmrc
- examples/lambda-invoke-v3/package-lock.json
- examples/lambda-invoke-v3/package.json
- examples/lambda-invoke-v3/serverless.yml
- examples/lambda-invoke-v3/src/handler.js
> chore: add example for lambda invoke with aws-sdk v3

- tests/integration/lambda-invoke-aws-sdk-v3/lambdaInvokeAsync.test.js
- tests/integration/lambda-invoke-aws-sdk-v3/src/lambdaInvokeAsyncHandler.js
- tests/integration/lambda-invoke-aws-sdk-v3/src/lambdaInvokeHandler.js
> test: fix lambda invoke with aws-sdk v3

- src/config/supportedRuntimes.js
Please merge to add support for latest python envs
> Add support for python3.10 and 3.11

- src/events/http/HttpServer.js
- src/events/http/lambda-events/LambdaProxyIntegrationEvent.js
- src/events/http/lambda-events/LambdaProxyIntegrationEventV2.js
- tests/integration/httpApi-headers/httpApi-headers.test.js
- tests/integration/httpApi-headers/serverless.yml
- tests/integration/httpApi-headers/src/handler.js
AWS API Gateway V2 sets `isBase64Encoded: true` and Base64 encodes `body` when the `Content-Type` is `multipart/form-data`.
Here's an event I captured from CloudWatch logs:
```
event: {
version: '2.0',
routeKey: 'ANY /{proxy+}',
rawPath: '/api/file',
rawQueryString: '',
cookies: [
'__Secure-access=REDACTED',
'__Secure-refresh=REDACTED'
],
headers: {
accept: 'application/json',
'accept-encoding': 'gzip, deflate, br, zstd',
'accept-language': 'en-US,en;q=0.9',
'content-length': '77988',
'content-type': 'multipart/form-data; boundary=----WebKitFormBoundaryfUJ9q6d7RNVDaA9B',
host: 'g9kcjnmfv2.execute-api.us-east-1.amazonaws.com',
origin: 'https://g9kcjnmfv2.execute-api.us-east-1.amazonaws.com',
referer: 'https://g9kcjnmfv2.execute-api.us-east-1.amazonaws.com/api/swagger.html',
'sec-ch-ua': …
```
> feat: convert multipart/form-data to base64 encoded payloads

- .github/workflows/nodejs.yml
> ci: remove node.js v21, add v22

- tests/integration/lambda-invoke-aws-sdk-v2/src/package-lock.json
- tests/integration/lambda-invoke-aws-sdk-v2/src/package.json
- tests/integration/lambda-invoke-aws-sdk-v3/src/package-lock.json
- tests/integration/lambda-invoke-aws-sdk-v3/src/package.json
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/package-lock.json
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/package.json
- tests/scenario/lambda-frameworks/apollo-server-integrations/app/package-lock.json
- tests/scenario/lambda-frameworks/apollo-server-integrations/app/package.json
- tests/scenario/lambda-frameworks/middy-lambda/app/package-lock.json
- tests/scenario/lambda-frameworks/middy-lambda/app/package.json
- tests/scenario/lambda-frameworks/serverless-http-with-express/app/package-lock.json
- tests/scenario/lambda-frameworks/serverless-http-with-express/app/package.json
- tests/scenario/lambda-frameworks/vendia-serverless-express/app/package-lock.json
- tests/scenario/lambda-frameworks/vendia-serverless-express/app/package.json
- tests/scenario/serverless-plugins/serverless-esbuild/app/package-lock.json
- tests/scenario/serverless-plugins/serverless-esbuild/app/package.json
- tests/scenario/serverless-plugins/serverless-plugin-typescript/app/package-lock.json
- tests/scenario/serverless-plugins/serverless-plugin-typescript/app/package.json
- tests/scenario/serverless-plugins/serverless-webpack/app/package-lock.json
- tests/scenario/serverless-plugins/serverless-webpack/app/package.json
> chore: bump test dependencies
