- README.md
- package.json
- src/index.js
With Serverless v0.4, running `sls offline start` sets the working directory to `node_modules/serverless-offline/src`, and when using the `-h` option, it tries to import certs relative to this working dir.
This PR is a basic fix, hope it will help others.
> Fix relative directory for importing TLS certs

- src/createVelocityContext.js
I have an use case where I need to pass and validate header data e.g. `Authorization`
The API Gateway produce capitalize headers:
```json
"headers": {
"Accept": "*/*",
"Accept-Encoding": "gzip, deflate",
"Accept-Language": "en-US",
"Authorization": "Bearer token"
}
```
but offline plugin produce (this is actually produce by node itself) lowercase headers:
```json
"headers": {
"accept": "*/*",
"accept-encoding": "gzip, deflate",
"accept-language": "en-US",
"authorization": "Bearer token"
}
```
and this cause an issue when I want to refer to object property in my lambda function e.g. `event.headers.Authorization` or use `Joi` validation so I have added code to keep headers compatibility with API Gateway.
> Normalize request.headers capitalization

- src/createVelocityContext.js
I am using principalId in my lambda function and for testing purpose I need to be able to use different principalIds so this pull request let me pass the principalId through env variable.
> Add option to pass principalId as env variable

- .editorconfig
- README.md
- src/index.js
I added two new CLI options, `--corsAllowOrigin` and `--corsAllowHeaders` in order to extend the CORS support of the plugin by way of HapiJs's `cors` configuration options.
**Important Note:** My changes will affect the output headers of `OPTIONS` requests, even if the user does not use the new CLI arguments.  The CLI arguments simply allow additional changes to be made by the user in case the defaults, that I provided, are insufficient.
See also: #39
--
I also added an `.editorconfig` in order to override my IDE's whitespace settings to those preferred by the project Owner so that I would not break the styles and conventions of the existing code.
> Added CORS options as CLI parameters

- src/index.js
- src/javaHelper.js
VTL is based on Java and exposes all standard Java APIs. So you can actually write things like this using regular Java String operations:
```
#if ( $foo.equalsIgnoreCase("bar") )
...
#end
```
This pull request adds some basic String operations by updating the JavaScript `String.prototype` - though prototype manipulation is evil, this is the only reasonable way of simulating a Java-like API. The following operations are added:
* String.prototype.contains
* ~~String.prototype.startsWith~~ (already part of Node 4.x)
* ~~String.prototype.endsWith~~ (already part of Node 4.x)
* String.prototype.replaceAll
* String.prototype.replaceFirst
* String.prototype.matches
* String.prototype.regionMatches
* String.prototype.equals
* String.prototype.equalsIgnoreCase
It is noteworthy that not all …
> Added Java-like String functions for better VTL compatibility

- src/index.js
Variable requestTemplate as empty string for `application/json` as shown [here](http://docs.serverless.com/docs/project-structure#section-functions) should pass the payload json variables through event if json variables are present as occurs in AWS. Referenced in #58 and #54.
> Pass json if provided when given empty velocity template

- src/index.js
API gateway only parses JSON payloads (at this time). This change will make serverless-offline behave the same as API gateway for other content types like 'application/x-www-form-urlencoded', ie. the payload is passed through untouched and available in body mapping templates through `$input.body`.
> Only parse JSON payload

- src/index.js
I've refactored a small bit of the code to expose HAPI's inject function which allows you to send a HTTP request without stating the server. This is useful for simulating HTTP requests in tests. I've also put together a package which uses this new capability called [serverless-offline-request](https://github.com/cameroncooper/serverless-offline-request).
Here's what I did:
- Removed const from serverlessLog so I can noop it out while running tests
- Replaced all instances of console.log() with a call to printBlankLine which again I can noop out during tests
- Pulled most logic from start() into a new _setup() function that both start() and inject() can call
- Fixed a bug where statusCode comes back as a string by using parseInt
> Expose HAPI's inject function

- src/index.js
Follow up on the PR in #73.
`application/json` is not the only MIME that is currently supported by APIG. I'm working with `application/vnd.api+json` and APIG seems to be parsing it well.
`application/vnd.api+json` is a registeded IANA format:
https://www.iana.org/assignments/media-types/application/vnd.api+json
Unfortunatelly, I haven't had a chance to check other derivatives like `text/json` but will do so. If you are aware of others let me know so I can test them too.
> Also parse a derivative of application/json

- src/index.js
I've added --host flag.
The added options is 
```
$ sls offline start --help
Simulates API Gateway to call your lambda functions offline
-p, --prefix
Adds a prefix to every path, to send your requests to http://localhost:3000/prefix/[your_path] instead.
-undefined, --host
The host name to listen on. Default: localhost
-P, --port
Port to listen on. Default: 3000
...
```
and usage is 
```
$ sls offline start --host 0.0.0.0
Serverless: Starting Offline: {stage}/{region}
...
Serverless: Offline listening on http://0.0.0.0:3000
```
and default option is 
```
$ sls offline start
Serverless: Starting Offline: {stage}/{region}
...
Serverless: Offline listening on http://localhost:3000
```
Note: I did not add -h of the short option because -h option already defined as --help option.
> Add --host flag to set IP address other than localhost to hapi

- README.md
Hi!
I'd like to propose a simple doc improvement. Open to feedbacks :)
> show how to install npm package for serverless v1 directly from github branch which makes it simpler than proceeding manually;
> doc: improve installation instructions

- src/createAuthScheme.js
Custom Authorization function is initialized with the environmental variables of last executed endpoint function issue fix
Fix for Issue #97
> Custom Authorization function is initialized with endpoint env-variables

- src/Endpoint.js
Currently if you don't set a custom request template, like
```
functions:
putSessions:
handler: handler.putSessions
events:
- http:
path: sessions/{uuid}
method: put
```
serverless-offline spits (v1) spits out an error like;
```
[offline] putSessions runtime nodejs4.3 
Serverless: Routes for putSessions:
[offline] Error: TypeError: Cannot read property 'template' of undefined
Serverless: PUT /sessions/{uuid}
Serverless: Offline listening on http://localhost:3000
```
... which is caused by `this.httpData.request` being undefined, hence the access to `this.httpData.request.template` fails even so it should be just a typecheck.
... and hence the catch is called, skipping application of default request & response template... which obviously is bad
> Handle undefined this.httpData.request

- src/index.js
When using custom authorizers and only specifying the function name, the default identitySource is `method.request.header.Auth` and doesn't function as expected because the default identitySource in serverless framework is `method.request.header.Authorization`. 
This PR just changes the default to match Serverless Framework to ensure correct functionality for those just using defaults in their configurations.
> Fix default custom authorizer identitySource to match serverless framework

- src/index.js
- test/integration/offline.js
This fixes #108 
There are a few ways this could be accomplished. Is this an acceptable solution?
This isn't a significant change, but when an error message is being returned from a serverless handler, if there's a "[XXX] Message" in the response, the status code on the response object will be set from this error object.
It makes no attempt to response the different patterns that serverless supports with API Gateway. I feel that this is out of scope of this PR and could be an interesting option by itself.
> Parsing [XXX] in error messages, to match serverless 1.0

- src/createAuthScheme.js
- src/index.js
As of serverless@1.1.0 the `authorizer.type` option has been removed, it is now explicitly set to `TOKEN` in template.
This PR removes `authorizer.type` option setting and checking from plugin so that it can be used with latest version of serverless.
> Update authorizer options

- src/createLambdaProxyContext.js
- test/unit/createLambdaProxyContextTest.js
As of aws-sdk@2.7.0 (and probably a few releases earlier) the `authorizer` is located inside `requestContext` when using lambda-proxy integration.
> Fix event authorizer property path in lambda-proxy context

- src/createLambdaProxyContext.js
- src/createVelocityContext.js
- src/utils.js
API Gateway always passes capitalize headers for lambda-proxy context so fix them as we do in velocity context. Also I extracted a function for capitalization and placed it in `utils`.
> Fix headers for lambda-proxy context

- src/createLambdaProxyContext.js
> Fix `resource` and `path` simulation for lambda-proxy contexts

- package.json
- src/index.js
This is a pretty simple solution that blanket allows any CORS preflight OPTIONS request. It could probably be improved upon to allow for customization, but for now it at least allows CORS development.
Fixes #94
> Properly respond to preflight OPTIONS requests for CORS

- README.md
- package.json
- src/index.js
Add a --location command line option to specify the directory from which the functions' files will be loaded.
Fixes #153
> 153 serve from subfolder

- src/index.js
With the new `--location` parameter it is possible to modify path to handlers. However this doesn't apply to authorization handlers so fix it too to while it is hot :fire: 😄
> Fix path to authorization handlers

- src/index.js
- test/integration/offline.js
Adds support for catch-all paths which were added to API gateway a few month ago:
https://aws.amazon.com/blogs/aws/api-gateway-update-new-features-simplify-api-development/
> Add catch-all path variable support

- src/index.js
Serverless allows the `ANY` method to be used for describing endpoints that can be invoked using any HTTP method,
This wasn't working in serverless-offline, the following fix modifies the `ANY` string to the `*` string expected by hapijs
> Allow use of the `ANY` method.

- src/createLambdaProxyContext.js
For requests that contain application/x-www-form-urlencoded data, the Content-Type and Content-Length headers need to be updated to reflect the JSON stringified data that is being sent in the body. This sets the Content-Type to "application/json" and sets Content-Length to the length of the JSON stringified data, if the request contains a payload.
> Update Content-Length and Content-Type headers based on the request body

- README.md
- src/index.js
With this PR `serverless-offline` will honor the endpoint CORS options and will use CLI CORS options as default values. If the CORS settings aren't set for a specific endpoint, no CORS headers will be added to response.
> Use endpoint CORS options to override default ones

- src/createAuthScheme.js
- src/createLambdaProxyContext.js
```
// authorizer response
{
"principalId": "yyyyyyyy", // The principal user identification associated with the token sent by the client.
"policyDocument": {
"Version": "2012-10-17",
"Statement": [
{
"Action": "execute-api:Invoke",
"Effect": "Allow|Deny",
"Resource": "arn:aws:execute-api:<regionId>:<accountId>:<appId>/<stage>/<httpVerb>/[<resource>/<httpVerb>/[...]]"
}
]
},
"context": {
"key": "value",
"numKey": 1,
"boolKey": true
}
}
// in handler
console.log(event.requestContext.authorizer.key);
console.log(event.requestContext.authorizer.numKey);
console.log(event.requestContext.authorizer.boolKey);
``` 
reference: [AWS docs: API Gateway custom authorizer output](http://docs.aws.amazon.com/apigateway/latest/developerguide/use-custom-authorizer.html#api-gateway-custom-authorizer-output) …
> #162 Add context object values to event.requestContext.authorizer

- src/index.js
Sets `process.env` variables from serverless.yml if they're defined globally under the `provider` key. For now, no support for variables defined locally within function definitions.
> fixes #161: load environment variables from serverless.yml

- README.md
- package.json
- src/index.js
This pull request adds an option to disable loading of environment variables. This enables usage of tools like PM2 and docker-compose to set the environment variables that would otherwise get overridden, while preserving the ability to deploy to aws with environment variables from serverless.yml.
> Added an option to disable the loading of environment variables

- src/createAuthScheme.js
this is the fix for issue #200 
this original validation regex did not allow header names with hyphens such as X-Gitlab-Token
> tweaked identitySource regex to support hyphens

- README.md
- src/index.js
This PR will allow use cases like this, that allow for automated testing within the scope of an active simulated server.
`sls offline --stage=integration --exec="npm run tests:integration"`
Ideally, this would have been a separate command (e.g. `sls offline exec`), but there's an ecosystem of serverless plugins that depend on the lifecycle hooks that are fired when sls-offline starts (e.g. Dynamo, Webpack), so this has been implemented as an option instead.
~~What I'm seeing is that if another plugin (e.g. serverless-dynamodb-local) is using the offline lifecycle, the database process is never told to shut down, so this process is stuck waiting for children to exit.  We'll need to think about emitting a lifecycle hook to those plugins so that they can exit cleanly.~~
A new lifecycle hook …
> Add exec option to execute shell commands in server scope

- package.json
- src/index.js
Looks like `ctrl+c` isn't actually halting the process after execution.
I'm making some assumptions from #203 this is how end should work. Let me know if this is inaccurate.
> fix process exit

- src/createLambdaProxyContext.js
Events sent by the real AWS API Gateway have `resourcePath` and `httpMethod` as properties
of `requestContext`. They duplicate the values of `resource` and `httpMethod` already present
one level above. See the docs [here](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html#api-gateway-simple-proxy-for-lambda-input-format).
Some libraries for implementing Lambda functions (in our case, we use [claudia-api-builder](https://github.com/claudiajs/claudia-api-builder))
rely on these fields being present. This patch adds these fields to the events generated
by serverless-offline.
> Include resourcePath and httpMethod fields in event.requestContext

- src/createLambdaProxyContext.js
- src/index.js
Changes on environment set
* Small fix on set environment from `serverless.yml` in `provider.environment` into `process.env`.
* Add support to set environment into `process.env` from `functions.$func-name.environment` in `serverless.yml` file like example below:
```yaml
provider:
name: aws
environment:
provider_var1: "provider_var1_value"
provider_var2: "provider_var2_value"
functions:
myfunction:
environment:
function_var1: "function_var1_value"
```
I think that this fixes #176
> Fix set environment process

- README.md
- src/index.js
Inspired by serverless-dynamodb-local, this PR lets you set options in `serverless.yml`.
> Allow setting options in serverless.yml

- src/index.js
Add support for nodejs6.10
[AWS nodejs6.10 Release announcement](https://aws.amazon.com/about-aws/whats-new/2017/03/aws-lambda-supports-node-js-6-10/?sc_channel=sm&sc_campaign=launch_Serverless_73c6f9ab&sc_publisher=tw_go&sc_content=Node_6_10_support&sc_geo=global&sc_outcome=launches&adbsc=social_launches_20170322_70997816&adbid=844682201593659393&adbpl=tw&adbpr=66780587)
AWS lambda released support for nodejs6.10. Serverless already allows you to deploy to it.
> add support for nodejs6.10

- src/javaHelper.js
Fat arrows have lexical this from parent scope. This undoes the breaking code introduced in https://github.com/dherault/serverless-offline/commit/3e8dd460231716339575106164aa454e8ec7e01a#diff-21b064378b3b7277f0da2780d78604ff.
> replaces fat arrows with functions so 'this' refers to global String object

- src/createAuthScheme.js
Add support to forbidden access if you deny on custom rule
On custom authorizer you can deny access, as example below:
```json
{
"principalId": "user",
"policyDocument": {
"Version": "2012-10-17",
"Statement": [
{
"Action": "execute-api:Invoke",
"Effect": "Deny",
"Resource": "arn:aws:execute-api:us-west-2:123456789012:ymy8tbxw7b/*/GET/"
}
]
}
}
```
Then, now serverless-offline can forbidden access if you deny access on custom rule like on AWS Lambda and API Gatweway, as below:
AWS Lambda response
```json
{
"Message": "User is not authorized to access this resource"
}
```
serverless-offline response
```json
{
"statusCode": 403,
"error": "Forbidden",
"message": "User is not authorized to access this resource"
}
```
Reference: https://docs.aws.amazon.com/apigateway/latest/developerguide/use-c …
> Add support to forbidden access if you deny on custom rule

- src/index.js
At some stage function events object went from empty list to `undefined` for lambdas without events (a totally valid scenario).
> Added short-circuit guard against functions that have no events

- manual_test/handler.js
- manual_test/serverless.yml
- src/index.js
#118 The endpoints still work as is even tho the authorizer is not supported.
Added manual tests for the ARN authorizer and custom function
authorizer.
> Added ignore the authorizer for the non custom authorizers.

- src/index.js
Added support for the upcoming `AWS_IAM` authorization type in Serverless: https://github.com/serverless/serverless/pull/3534
Supporting other endpoint types such as `HTTP`, `HTTP_PROXY` and `MOCK` are *not* part of this pull request.
> Added support for authorizer type `AWS_IAM`

- test/support/RequestBuilder.js
- test/unit/createLambdaProxyContextTest.js
I was fiddling around with a different issues, and incidentally added a couple of tests around the default headers added in the Lambda Proxy request context:
If the body is present:
* calculate and add a `Content-Length` header
* set a default `Content-Type` of `application/json` if none is provided
No underlying library behaviour is changed.
> Add test for default content-type and content-size

- .travis.yml
- src/index.js
- test/integration/offline.js
Even setting my function handler timeout to 300 seconds my connections was closing after 120 seconds.
That's because of node socket default timeout (https://hapijs.com/api#route-options, navigate to timeout -> socket or search for `2 minutes` on this page).
This PR sets route config `timeout.socket` to `false` so we can delegate the timeout just to the  `_replyTimeout` function.
Also I am adding a debug log for `funOptions` because I think it's an important value to see when debugging.
> Disabling node socket timeout

- src/createAuthScheme.js
- src/index.js
Currently, the environment variables set in the `serverless.yml` are not available in the custom authorizers implemented. This PR aims to resolve that issue.
> Service wide environment variables passed on in authorizer

- package.json
- src/createLambdaProxyContext.js
This was sparked from [vandium-io/lambda-event-identifier](https://github.com/vandium-io/lambda-event-identifier) not properly supporting serverless-offline due to a missing apiId in the requestContext.
Looking at some lambda proxy examples though, this could be useful to include for future compatibility reasons, if other libraries are checking the requestContext data as well.
> Add apiId to requestContext

- manual_test/handler.js
- manual_test/serverless.yml
- package.json
- src/createLambdaProxyContext.js
- test/support/RequestBuilder.js
- test/unit/createLambdaProxyContextTest.js
Re-encoding path params that hapi auto decoded to match AWS behavior. Fixes #265
> Ensure path parameters are url encoded to match aws behavior

- src/createAuthScheme.js
When invoking a custom authorizer, supply the requested path
instead of the configured endpointPath. This matches AWS
behavior.
> methodArn should contain request.path

- src/createAuthScheme.js
This is to more closely match the behavior of API Gateway.
> Remove stage prefix from auth event methodArn

- src/index.js
Requests with binary data may need more than 1MB, and there is no such 1MB limit in AWS API Gateway.
Closes #282
> Increase payload size limit from 1MB default to match AWS 10MB limit.

- package-lock.json
- package.json
- src/createAuthScheme.js
The crypto module used has been removed from NPM.
It does not need to be required, and is now a `node built-in` as specified here: https://www.npmjs.com/package/crypto
This PR removed crypto as a dependency from `package.json`
> removed npm crypto from dependency and used node-native crypto

- src/createAuthScheme.js
Pretty frequently have issues with the authfunc having some error and it gets swallowed with a pretty unhelpful message. I'm constantly having to add a debug print of the error to find out what the issue is. 
I think this change will improve developer's lives (at least mine!)
The change adds the following to the debug output (example):
`[offline] create authorization function handler Error: Cannot find module '../authorize'`
> Don't swallow error message when creating auth function handler

- src/createVelocityContext.js
Api Gateway's request templates use the header object to get the values for the headers.
> Use header (singular) to follow API Gateway conventions

- src/index.js
> enforces upper case on method names for protected routes mapping

- package.json
- src/createAuthScheme.js
Now that serverless supports request type authorizers, it makes sense for this plugin to also support them. This PR fixes #326
> Adding support for request-type authorizers

- README.md
I had issues running serverless-offline with flow types in my code until it occurred to me that I might need to update my `babelOptions` - once I figured it out, I thought I'd document the fix and submit a PR. Let me know if there are any changes you'd like me to make. Thanks!
> Update README: add usage with flow

- src/createAuthScheme.js
Environment variables that are defined for an authorizer function are not set when the authorizer function runs.
Given this serverless.yml:
```yml
provider:
environment:
SOME_VAR: 'foo'
functions:
hello:
handler: index.hello
events:
- http:
path: hello
method: get
authorizer: authorizerFunc
authorizerFunc:
handler: index.authorizerFunc
environment:
OTHER_VAR: 'bar'
```
`process.env.OTHER_VAR` will be `undefined` when the authorizer function runs.
----
#254 assigned environment variables on a per request basis, so that environment variables that were defined on a specific function would not be overridden by variables defined for a different function. But, this meant that environment variables were not set for authorizer function(s).
#263 partially fixed environment variables for authorizer …
> Include environment variables defined for the authorizer function when the authorizer function runs.

- src/index.js
Log error in _reply500 if stack trace is empty. Fixes #361.
I'm still not sure though, maybe error should be logged unconditionally instead? Because I see there're two error messages generated: one comes from the exception that triggered error 500 generation, the other comes from the code that handled that exception. It's a little confusing, what would be better…
> improved error logging

- src/createLambdaProxyContext.js
- src/index.js
- test/integration/offline.js
- test/support/RequestBuilder.js
This change introduces request.rawPayload to the Hapi request
and uses that if request.payload is not a string.
Before, JSON.stringify(JSON.parse(request.payload)) was being
used, which is not the same as the rawPayload that should be
passed along.
---
I noticed when using the Intercom API that serverless-offline was stripping out newlines and tabs from the request body, which makes it impossible to test webhooks that use a `x-hub-signature`. I checked and the current behavior from serverless-offline does not emulate the behavior of AWS Lambda in this respect.
I have changed `createLambdaProxyContent` so that it passes the raw payload through instead of stringifying the payload.
I have also added some tests that fail on the current version of serverless-offline.
> Stop stripping newlines and tabs from body

- src/createAuthScheme.js
- src/index.js
- moves the strict check to be called only if the type === 'token' (not request)
- capitalizes headers in addition to the lowercase version because on AWS the headers are always capitalized
- fixes a couple of lint errors
Fixes https://github.com/dherault/serverless-offline/issues/375
> Improves support authorizer.type == request

- src/authCanExecuteResource.js
- src/authMatchPolicyResource.js
- src/createAuthScheme.js
- test/unit/authCanExecuteResourceTest.js
- test/unit/authMatchPolicyResourceTest.js
As reported in #340 custom authorizers currently only look at the first statement in the returned policy and do not inspect the whole of the policy returned by the authorizer function.
This PR adds support for more complex policies that would be more common in the real world. Wild cards are supported in resources.
> Add support for complex policies with wildcards

- package-lock.json
- package.json
- src/index.js
- Avoid aws errors when use aws service in serverless.yml like ssm;
- Don't load serverless environment variables when the flag noEnvironment is passed.
> Added support to noEnvironment flag

- package.json
- src/index.js
This PR fixes https://github.com/dherault/serverless-offline/issues/383
Serverless-offline `3.20` breaks usage of aws resources. This resolves that by only overriding environment variables for AWS credentials when specifying the `--noEnvironment` flag,
> Fix for broken AWS resources

- src/index.js
When calling lambdas functions using API Gateway at AWS environments the environment variable `_HANDLER` is set.
Some plugins are using this variable but it's not possible to use them with `serverless-offline` because the lack of this variable (see: https://github.com/trek10inc/serverless-secrets/issues/22).
Also I think we want to keep `serverless-offline` environment as similar as possible to a real AWS environment.
> Adding process.env._HANDLER

- src/index.js
- src/utils.js
- test/unit/utilsTest.js
Hello,
This PR resolves #230 with a quick fix change to allow `serverless-offline` to handle `multipart/form-data` which is surely never a `utf8` string in most use cases.
I didn't have a fantastic general solution but it has come up a couple of times from people out there per the referenced issue.
I did replace a fork that I use to test this and found that it works as expected with test data that is used to send to aws.
> Adds special encoding for multipart/form-data

- package.json
- src/functionHelper.js
- src/index.js
- src/ipcHelper.js
This feature stemmed from issues getting our app working properly with cache invalidation enabled. Old handlers weren't being removed fully, database connections not being closed, etc.
Instead, I've gone the route of allowing each handler to run in its own node process, which is simply destroyed after the request returns. (Or kept running/cached if `--skipCacheInvalidation` is provided)
This feature is activated using `--useSeparateProcesses`. This does add a bit of overhead to each request, but it's useful for avoiding restarting serverless every time a change is made.
If you're interested in having this feature upstreamed, I'll go fix the few remaining `TODO`s and clean it up.
(This also addresses the issues outlined in #313)
> Add option to run handlers in separate node processes

- package.json
- src/index.js
- test/integration/offline.js
This change will allow using handlers with await/async and handlers returning `Promise` for `nodejs8.10` runtime. More information on await/async handlers are available in [AWS Lambda docs](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html).
Fixes #384
> Add async handler support for nodejs8.10 runtime

- package-lock.json
- package.json
Pulls in 8.2.1 of jsonwebtoken, this will remove a low severity vulnerability in hoek. See https://snyk.io/vuln/npm:hoek:20180212
> Upgrade jsonwebtoken

- package.json
- src/index.js
Fix https://github.com/dherault/serverless-offline/issues/298
> Support another HTTP Proxy methods

- package.json
- src/index.js
Currently binary responses are only supported when using the lambda-proxy integration. This PR adds support when using the lambda integration. The usage is compatible with https://github.com/ryanmurakami/serverless-apigwy-binary
> Add binary support when using lambda integration

- README.md
- src/index.js
As can be seen in #334, there is a weird issue when trying to expose headers and the `origin` request header is present. This is probably due to something going on with `hapi` (not quite sure where though). This PR adds a CLI option, `corsExposedHeaders` to allow general setting of this value.
> Add exposed headers

- package.json
- src/createLambdaProxyContext.js
- test/unit/createLambdaProxyContextTest.js
I have a simple case where firefox and chrome use different capitalization for the content-type header; serverless-offline looks only for 'Content-Type' and so in local cross browser testing code that relies on this header [1] I'm getting 'application/json' instead of a multipart form-data / boundary header.
Specifically Firefox sets 'content-type' versus Chrome setting 'Content-Type'. 
My fix is simple, and I do not actually agree with this as a course of action. I think it would be more correct to normalize headers earlier in the request process so that everything downstream can be written to support that normalization. I'm happy to take a step back and evaluate what that work would take, however it feels risky as I'm very new to the code of the project. AWS Lambda appears to normalize …
> read content-type header in a case insensitive manner

- src/index.js
- test/integration/offline.js
Changed the way that the response headers are set, and opted to use the response.header function rather than setting response.headers directly. This allows for some of the headers which hapi sets to be handled better (e.g. CORS)
> Use Response.header rather than Response.headers

- package.json
- src/index.js
Possibly related to #364 
**Issue:** Currently serverless-offline is [adding](https://github.com/dherault/serverless-offline/blob/master/src/index.js#L372) a `/` before every path it pushes into the `protectedRoutes` array. So paths that already have a `/` such as `/users` end up as `//users` in the array. 
When a call is made to '/users', it's not registering as protected because [_.includes(['GET#//users'], 'GET#/users')](https://github.com/dherault/serverless-offline/blob/master/src/index.js#L475) returns false.
**Fix:** This change makes it so that the 'protected' attribute works on with functions whose paths begin with `/` and those that don't.
> Fix protected routes

- src/createLambdaContext.js
- src/index.js
Closes #405 
The warning is legit but the message is a bit off.
The problem is very simple. However, the solution is very hard.
The problem, as pointed out in the issue, is at https://github.com/dherault/serverless-offline/blob/f3903a76d8ccd02550b5a1b5a733224abee3a50f/src/index.js#L813-L819
The function is async so returns immediately and returns a promise. Thus, being resolved as a promise.
Asynchronously, at some point in the future, the callback will be called. Thus, getting the warning.
I don't think there is any way to know when the callback will be called, if ever. So the only thing that we can do is to add a better warning message.
This is not a problem that affects only this library. Running async handlers that use the callback in AWS lambda also produce weird issues and doesn't …
> Show the right waning on promise vs callback conflict.

- src/createLambdaProxyContext.js
- src/utils.js
- test/support/RequestBuilder.js
- test/unit/createLambdaProxyContextTest.js
Related to #428 
Querystring parameters with the same name are merged into arrays as Hapi feature described [here](https://futurestud.io/tutorials/hapi-how-to-use-query-parameters#multiplequeryparametersofthesamename). API Gateway instead get only the last parameter, because it requires parameter names are unique. 
E.g.
```
URL: /my-url?param=1&param=2
Expected value for event.queryStringParameters: {param: 2}
Actual value for event.queryStringParameters: {param: [1, 2]}
```
In `createLambdaProxyContext`, every parameter in `request.query` is mapped into his last item.
> Normalize Hapi queryParameters to be compliant with API Gateway

- src/index.js
The lifecycle events are called one after another anyway, there is no need to handle cleanup in the `init` lifecycle stage.
Fixes #436.
> Only call end() from the corresponding lifecycle hook

- package-lock.json
- src/createLambdaProxyContext.js
- test/unit/createLambdaProxyContextTest.js
Allow for the ability to provide a Cognito identity id via request headers. 
see #406
> add cognito identity id header

- README.md
About as minor of a nitpick as it gets, but wanted to keep the readme's mention of currently supported Node versions by AWS Lambda in sync.
- Update mention of supported Lambda versions to reflect deprecation of Node v4.3.2 and new support of Node v8.10.0, and add relevant link to AWS docs
- Change subheading "Token Authorizers" to "Token authorizes" for consistency with other subheadings (`</ocd>`)
> Minor Readme update to reflect Node v8.10.0 Lambda support

- package.json
- src/index.js
- test/integration/offline.js
Please see #459 
I have also applied the JSLint, which automatically fixed a few methods that were not compliant.
> adding check to prevent 500 in AWS Lambda when json body is not stringified

- package.json
- src/index.js
Let's say I want to define two functions that both use the same environment variable with different values. One is triggered by HTTP and the other is triggered by a schedule using the [serverless-offline-scheduler](https://github.com/ajmath/serverless-offline-scheduler) plugin:
```
plugins:
- serverless-offline-scheduler
- serverless-offline
functions:
httpFunc:
handler: httpFunc.func
environment:
ENV_VAR: val1
events:
- http:
path: http-func
method: get
scheduledFunc:
handler: scheduledFunc.func
environment:
ENV_VAR: val2
events:
- schedule:
rate: rate(10 minutes)
```
As seen on [this line](https://github.com/ajmath/serverless-offline-scheduler/blob/master/lib/scheduler.js#L86), the `serverless-offline-scheduler` plugin sets `process.env` to the environment variables provided to the …
> fix: prioritize handler environment variable values over the originals

- README.md
- package.json
- src/index.js
- src/ipcHelper.js
- test/integration/offline.js
- test/unit/createLambdaProxyContextTest.js
There is an issue when using the `--useSeparateProcesses` flag in error reporting. When using the `--useSeparateProcesses` flag, the lambda function handler is loaded in a separate process, and serverless-offline communicates with this child process over IPC. When an `unhandledException` error occurs in the handler code, the Error object wasn't being properly serialized. Then, due to the asynchronous loading of the handler code (require() in the ipcHelper), fatal errors were not being reported correctly to the request-client in the same way that they are for non-separate-processes [handler loading](https://github.com/dherault/serverless-offline/blob/master/src/index.js#L540).
This PR implements the simplest fix to address these issues. It unfortunately does not include a test because …
> fix: error feedback when using --useSeparateProcesses flag

- src/createAuthScheme.js
- src/index.js
AWS API Gateway allows providing an API key from authorizer functions: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-usage-plans.html#api-gateway-create-usage-plans
This fixes the bug that API keys returned from authorizer functions were not considered valid by serverless-offline.
> Check if usageIdentifierKey returned by an authorizer is a valid API key

- README.md
- src/createLambdaProxyContext.js
This pull request was made to make life simpler for people using remote authorizers (lambda-arn).
> Added option to set "authorizer"-property using process.env.AUTHORIZER

- package-lock.json
- package.json
- test/support/OfflineBuilder.js
This should address #440.
`npm audit` output: 
<details>
```json
{
"actions": [
{
"module": "hapi",
"resolves": [
{
"id": 532,
"path": "hapi>joi>moment",
"dev": false,
"optional": false,
"bundled": false
},
{
"id": 532,
"path": "hapi>statehood>joi>moment",
"dev": false,
"optional": false,
"bundled": false
},
{
"id": 530,
"path": "hapi>subtext>content",
"dev": false,
"optional": false,
"bundled": false
},
{
"id": 530,
"path": "hapi>subtext>pez>content",
"dev": false,
"optional": false,
"bundled": false
}
],
"target": "17.5.4",
"action": "install",
"isMajor": true
},
{
"action": "install",
"module": "mocha",
"target": "5.2.0",
"isMajor": true,
"resolves": [
{
"id": 534,
"path": "mocha>debug",
"dev": false,
"optional": false,
"bundled": false
},
{
"id": 146,
"path": "mocha>growl",
"dev": …
```
> Update dependencies to fix critical vulnerabilities

- manual_test/README.md
- manual_test/subprocess.js
- src/index.js
Hey-oh! 👋 
Big thanks to the whole team of this project for doing such an awesome work!
I recently stumbled upon the issue where the hapi server that is used by `serverless-offline` would just go rogue and continue running even when the `sls offline` should be shut down correctly with `SIGTERM`. 
I tracked it to `serverless-offline` not handling `SIGTERM` as another signal for calling `this.end` and as the fix was pretty obvious I decided to open PR right away, instead of creating an issue first
ℹ️ This is just a suggested solution and I'm happy to adjust it if you feel that some changes are needed. If you want me to just open an issue instead of creating the PR, this is also fine by me 😊
> Gracefully shut down hapi server on SIGTERM

- package.json
- src/ipcHelper.js
Support for async handlers in nodejs8.10 runtime was added [here](https://github.com/dherault/serverless-offline/pull/398) and works by checking if the handler returned a promise and if so, hooking it up to the "done" callback. However it doesn't work if `useSeparateProcesses` option is true. In that case the handler is created in a child process with ipcHelper.js which calls the handler itself and has to link the callback up across the IPC channel. In order for async handlers to be supported in the child process, ipcHelper also needs the logic to hook up the promise returned by the handler to the callback.
> Fix async handler support for handlers running in separate processes

- package.json
- src/Endpoint.js
- src/index.js
- src/offline-endpoint.json
- test/integration/offline.js
Only supports static string values for successful responses.
AWS requires double-quoted strings as header values to avoid "Invalid mapping expression specified" errors when trying to interpret them as an integration response variables (e.g. integration.response.header.Content-Type).
<sub>Fixes #493</sub>
> Set response headers defined in serverless config 

- README.md
- src/functionHelper.js
- src/index.js
allow for a customized cache invalidation mask. this is especially useful when testing external libs that are npm link'd as `cacheInvalidationIgnore: /node_modules/(?!my-lib/)`
> add `cacheInvalidationIgnore` option

- package.json
- src/createLambdaProxyContext.js
- src/utils.js
- test/unit/createLambdaProxyContextTest.js
Possible solution for [Issue 469 - query params inconsistencies with api gateway for duplicate keys](https://github.com/dherault/serverless-offline/issues/469).
Aligns with AWS' implementation of `multiValueQueryStringParameters` as described over [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format).
> added support for multiValueQueryStringParameters

- src/index.js
- test/integration/offline.js
This should fix #503. I'm still not sure if I understood how this should work correctly, but it seems to do what I wanted it to do. Any guidance in case I missed something would be welcome.
I still don't understand why `authStrategyName` passed to `routeConfig` needs to be set to `null` in case `noAuth` is set. It doesn't seem to do anything, but I'm afraid to remove it because I'm not sure if all use cases are covered by tests.
> Fix noAuth option not working

- README.md
- package-lock.json
- package.json
- src/index.js
- test/integration/offline.js
Hi,
in our environment, we experienced the issue that we have some strange cookies on our site to send to a running serverless-offline instance via GET. The server then responds with bad request. This behaviour can be configured in the underlying hapi.js-instance. 
I added a param to trigger this, of course optional and tested. 
I also took the time and fixed 3 eslint-warnings.
Would appreciate to see this in a future version!
Thx in advance.
> Feature: param to disable cookie validation in hapi.js

- README.md
- package.json
- src/createLambdaProxyContext.js
- test/unit/createLambdaProxyContextTest.js
By merging this we allow a developer to be able to retrieve a userId from the congitoAuthenticationProvider and in my case it allows me to load in my userData from my local dynamodb.
> Add cognito-authentication-provider as header

- src/index.js
It was confusing that starting `serverless offline` with `--noAuth` flag still said that I need to use `x-api-key` header. I wasn't sure if it'd make more sense to remove the message with key altogether or just add that authorizers are disabled. I'm open for suggestions / better wording.
> Change startup log message if noAuth is enabled

- src/createVelocityContext.js
- test/unit/velocityContextTest.js
After experimenting with different implementations of decoding query strings, Node's `decodeURIComponent()` seemed to be the best fit. The only issue with it is the `+` sign, which should be converted into a space. We do that manually before calling `decodeURIComponent()`.
Added `velocityContextTest.js` to fine tune different implementations.
Fixes #521
> Improved emulation of APIG's urlDecode velocity template function

- src/createLambdaProxyContext.js
Should an invalid token be passed in the headers, the handler fails with an uncaught error. The error should be ignored instead.
> Prevent uncaught error with invalid token

- .travis.yml
removes unsupported (end-of-life) versions of node.js from travis: v5, v7, v9
adds supported versions of node.js: v10, v11
additional information: https://github.com/nodejs/Release
> adds supported and removes unsupported versions of node for travis tests

- manual_test/serverless.yml
- package.json
- src/authFunctionNameExtractor.js
- src/index.js
- test/unit/authFunctionNameExtractorTest.js
This PR includes basic support for handling authorizerId in cusom authorizers, in the current version it  is not recognized as an external authorizer. With the PR it is recognized and skipped like the other externals identifier.
> Support for authorizerId

- package-lock.json
- src/authMatchPolicyResource.js
- src/createAuthScheme.js
- test/unit/authMatchPolicyResourceTest.js
The event object for an authorizer request in the live environment has a requestContext object. I am using that to extract a few variables and therefore need them in the serverless-offline plugin as well. 
Added the ones that are easy to gather/have already been included in the event.methodArn string.
https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format has details on the requestContext format.
> Add some requestContext to auth event and fix resouce with colon

- src/functionHelper.js
Retained cache:
There's also an issue on the node repo talking about the cache issue https://github.com/nodejs/node/issues/8443
> remove nested require.cache under functionHelper's children

- package.json
- src/functionHelper.js
- src/index.js
- src/ipcHelper.js
This solves a few issues, notably:
- The flag `--useSeparateProcesses` along with `--skipCacheInvalidation` would leave these handlers running after exit. Added a cleanup hook to `functionHelper`.
- Reimplements removing `undefined` values from `process.env` to match the behavior before commit c5cba66652ddec8e3b73c9fea5d0834aac783ef1
- Implemented `getRemainingTimeInMillis` and other properties that have been added to `createLambdaContext`.
- Clarifies naming issues with `function` vs `handler`.
> Ensure external handlers are cleaned up on exit

- src/index.js
Allow users to provide environment variables outside of node without  the --noEnvironment flag blowing them away
> --noEnvironment Upgrade

- README.md
- package-lock.json
- package.json
- src/index.js
- src/requestBodyValidator.js
- test/unit/requestBodyValidatorTest.js
If request validation is enabled for http lambda-proxy integration,
the request body is validated against the request model.
```
npm test
120 passing (551ms)
```
I've linked my local experimental project to serverless-offline that has the changes in this PR. I've used the following serverless.yml file:
```
service: serverless-hello-world
plugins:
- serverless-offline
- serverless-reqvalidator-plugin
- serverless-aws-documentation
provider:
name: aws
runtime: nodejs6.10
custom:
documentation:
api:
info:
version: v0.0.0
title: Experimental API
description: This is an experiment
models:
-
name: HelloModel
contentType: application/json
schema:
type: object
properties:
message:
type: string
minLength: 2
required:
- message
functions:
helloWorld:
handler: handler.helloWorld
events:
- http: …
```
> Add request body validation

- package-lock.json
- src/index.js
Prevent overriding exported AWS_PROFILE with fake 'dev' explicit credentials when using --noEnvironment option
> Prevent overriding exported AWS_PROFILE 

- package-lock.json
- package.json
- src/Endpoint.js
- src/index.js
- src/javaHelpers.js
unfortunately this causes a deprecation warning by an outdated `eslint-config-nelson`:
```cli
(node:12500) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "node_modules/eslint-config-airbnb-base/index.js")
```
not sure if you feel heart broken about removing the plugin?
> upgrade eslint and eslint-plugin-import

- src/createAuthScheme.js
I think that the fix is pretty self-explanatory.
If the auth header is missing you get `TypeError: Uncaught error: Cannot read property 'match' of undefined` and you shouldn't.
Please ask if any clarification is needed.
> Fix Scheme creation to not throw on missing auth header

- README.md
- src/index.js
PR #589 added request body validation for lambda-proxy integration, but not for lambda integration. This PR adds request body validation for the two types of integrations.
> Add request validation for lambda integration

- test/unit/functionHelperTest.js
As windows use different path separators 2 tests were failing. 
This pr addresses them.
> Fix failing tests on windows 

- package.json
- src/index.js
Fixes a bug where `stage` will always be set to `service.provider.stage` and **ignore** the custom YAML option (`custom.serverless-offline.stage`) if provided.
The same bug existed for `region`.
> Fix stage and region option precedence bug (Closes #338)

- src/index.js
My serverless lambda responses have no headers configured which was causing this error:
```javascript
Debug: internal, implementation, error
TypeError: Uncaught error: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at createLambdaContext (/api/client/node_modules/serverless-offline/src/index.js:793:24)
at Object.fail (/api/client/node_modules/serverless-offline/src/createLambdaContext.js:17:21)
at ChildProcess.process.on.code (/api/client/node_modules/serverless-offline/src/functionHelper.js:68:19)
at ChildProcess.emit (events.js:197:13)
at ChildProcess.EventEmitter.emit (domain.js:504:23)
at maybeClose (internal/child_process.js:988:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```
Example Lambda:
```yaml
example_lambda:
handler: …
```
> Fix detection of undefined endpoint response headers

- src/createVelocityContext.js
background: https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/
> Replace deprecated Buffer constructor call with Buffer.from.

- README.md
- src/functionHelper.js
- src/index.js
`serverless-offline` attempts to spawn a child process to run the `sls` command, which breaks if a user does not have Serverless installed globally. This pull request allows a user to optionally specify the path to their Serverless install.
Usage:
```
$ serverless offline                                  # Defaults to global install
$ serverless offline --binPath node_modules/.bin/sls  # Project install
$ serverless offline -b /usr/local/bin/sls            # Short-hand flag
```
There were not currently any tests that ensured the validity of the `spawn('sls', ...)` call, ie. changing that to `span('asdf asdf', ...)` still had passing test suite.
See https://github.com/dherault/serverless-offline/issues/645 for discussion
> Add --binPath to options

- src/functionHelper.js
- src/index.js
closes https://github.com/dherault/serverless-offline/issues/539
background:
`this.requests` is adding a `request property` with each new request and doesn't remove it (ever).
> fixes memory leak

- package.json
- src/index.js
The call to this.end() would terminate the process before 'offline:start:end' could be consumed by downstream plugins. When running sls offline that can be expected, but docs say that 'sls offline start' will provide the init and end hooks for other plugins to consume.
This just moves the entry points for start and the base offline commands to different functions so that this.end doesnt terminate when other plugins are expecting to run off the 'end' hook.
> Fix hooks for sls offline start

- src/index.js
- test/integration/offline.js
It looks like when the lambda handler is async and defers execution, the function scheduled in the setTimeout call would clean up the requests object.  The problem is that the handler is still in flight and when it resumes execution, the request object is gone.
This fix keeps the original behavior when the handler is not created or is not a promise, but will try clean up on a promise continuation if it is a promise.  I'd like to use `.finally(cleanup)` but that isn't supported in node 8, so that's why I went with `.then(cleanup, cleanup)`.  It looks like we don't care about the resolved value, so I think that should work fine.
> Cleanup on a promise continuation when handler is async to fix #659

- src/index.js
- test/integration/offline.js
This should address the second part of #659 where cleanup wasn't getting called properly for callback based requests that deferred execution.
I'm not sure what the original intent of the cleanup method was and this feels a bit like whack-a-mole. That said, all tests pass (including two new ones) and the test application linked in the issue works correctly. Speaking of tests, I have one test around error handling and I'm not sure how to suppress logging of the error to the screen while running the tests. Not sure if that matters, but it doesn't look nice.
> Call cleanup in callback and error handler instead of finally block.

- src/index.js
Related to #204 and #409 
HEAD routes defined in resources block should also be skipped (until a better solution)
> skip HEAD routes defined in resources

- .travis.yml
https://github.com/nodejs/Release#nodejs-release-working-group
> Remove node.js v11.x (end-of-life) from travis

- src/index.js
closes: https://github.com/dherault/serverless-offline/issues/683
hapi server callback is now a promise. not quite sure about the error handling recommendation. (console.error, process.exit) previously the callback error being wrapped in a promise was not being handled down the chain as far as I could tell (might have missed it).
> Fix server start handling (callback -> promise)

- test/integration/offline.js
converts (modernizes) all asynchronous tests to use `async functions`.
in a nutshell:
- switch callback `(done) =>` to callback `async () => `
- Promise `.then(res => ...)` to `const res = await ...`
- remove `done()` call
> Convert asynchronous mocha tests to use async functions

- package.json
- src/createLambdaProxyContext.js
- test/support/RequestBuilder.js
- test/unit/createLambdaProxyContextTest.js
Add requestTimeEpoch to requestContext
> Add requestTimeEpoch to requestContext

- README.md
- package-lock.json
- src/index.js
Their was no way to invoke lambdas locally.
```
const builderLambdaParameters = {
FunctionName: 'vidiff-services-dev-builder',
InvocationType: 'Event',
LogType: 'None',
Payload: JSON.stringify({ buildId: build._id }),
}
await lambda.invoke(builderLambdaParameters).promise()
```
Add a new route for each handler to support `lambda.invoke`:
```
Serverless: Starting Offline: dev/eu-west-3.
Serverless: Routes for graphql:
Serverless: POST /graphql
Serverless: POST /{apiVersion}/functions/vidiff-services-dev-graphql/invocations
Serverless: Routes for builder: (NOTE: this route has no event)
Serverless: POST /{apiVersion}/functions/vidiff-services-dev-builder/invocations
Serverless: Offline listening on http://localhost:3111
```
And use `aws-sdk` like this:
```js
const lambda = new AWS.Lambda({ …
```
> Add support for lambda.invoke

- src/index.js
Here's a simple new feature: enter "rp" in the console of a running serverless-offline instance to replay the last request. Inspired by nodemon's "rs" to restart. :)
> [FEATURE] Replay last request

- src/index.js
when, the lambda payload is `JSON.stringify(null)` serverless-offline would throw.
> Fix event.isOffine bug

- src/createAuthScheme.js
Escape identity validator expression;
Do not require grouping and return original token;
> Fix #715 Fix expression validator

- manual_test_websocket/main/test/e2e/ws.e2e.js
- src/ApiGatewayWebSocket.js
As mentioned [here](https://github.com/dherault/serverless-offline/pull/711#issuecomment-507386379), the websocket implementation is missing a way to close the websocket from the server using the @connections URLs. This merge requests adds that feature.
To close a websocket, as per AWS (very scarce) documentation, call `DELETE http://<websocket_host>/@connections/<connectionId>`
> Add DELETE route to close a websocket connection

- src/ApiGatewayWebSocket.js
If an error occurs in the $connect action handler, AWS does not let the connection be established. In order to mimic that behaviour, let's close the connection if the $connect handler throws.
see https://github.com/dherault/serverless-offline/pull/711#issuecomment-506977431
> close connection on error in $connect action handler

- src/ApiGatewayWebSocket.js
As `req.url` only contains the relative URL, the [base URL parameter](https://nodejs.org/api/url.html#url_constructor_new_url_input_base) (or absolute input URL, either of those must be given) was missing from the `new URL(req.url)` call, which causes a crash on $connect action as it is unable to parse the query string parameters and throws with ERR_INVALID_URL.
> fix: missing base in URL() constructor

- src/ServerlessOffline.js
Disclaimer: this is copy/pasted from [steve-winter/serverless-offline](https://github.com/steve-winter/serverless-offline/pull/1) which seems to be accidentally be created against his own master branch.
This PR adds golang to the supported runtimes.
I've tested it via 
```
npm i --save phux/serverless-offline#go_serviceruntime
```
And it seems to work fine.
> feat: add go to supported runtimes

- src/ApiGateway.js
Handled `undefined` and `null` reponseParameter values.
Closes #758
> Fixed undefined and null responseParameter values

- src/index.js
Removing `unhandledRejection` listener currently breaks exit code handling in Serverless 1.48.1+ -> https://github.com/serverless/serverless/issues/6441, it technically turns off some important part of Serverless logic.
Serverless no longer forces process exit on `unhandledRejection`, so merging this in won't introduce a regression to #255 (which also should rather have been processed in context of `serverless` repo, not here)
--- 
In future Serverless may force process exit on `unhandledRejection` but only if there were no listeners registered for it, which is on pair with Node.js deprecation warning:
```
[DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit …
```
> Do not remove unhandledRejection listeners as it breaks Serverless

- src/handler-runner/ServerlessInvokeLocalRunner.js
Two issues covered here:
**Incorrect treatment of prints as responses**
The previous JSON detection assumed that there would be one and only one valid JSON object printed to `stdout` from the process. If you printed something that looked like the response, it would often throw bad JSON exceptions and fail the invocation.
An example:
```python
def my_handler(event, context):
my_response = { "statusCode": 200, "body": "hi" }
print(my_response)
print("hello!")
return my_response
```
would end up failing while attempting to parse the following results string:
```
'{ "statusCode": 200, "body": "hi" }hello!{ "statusCode": 200, "body": "hi" }'
```
**Extra newlines in large responses**
Less clarity here... looks like it has something to do with buffer chunking? In any case, I was getting …
> UpdateJSON response detection from stdout in local invocations

- src/api-gateway/authMatchPolicyResource.js
We are using a resource policy("`arn:aws:execute-api:*:*:*`") that works fine on aws but not when using serverless, this took some time to figure out. Could we add it?
Image of aws documentation where this structure is used:
https://imgur.com/iQX17pt.png
> Add another style of policyResource

- src/config/offline-default.req.vm
- src/createAuthScheme.js
- src/createLambdaProxyEvent.js
- src/createVelocityContext.js
Serverless has this (not very-well documented) feature that passes lambda authorizer context data into the subsequent lambda execution event as `enhancedAuthContext`.
See https://github.com/serverless/serverless/issues/4374 for more info about this feature.
This is the type of event available in live environments, that serverless-offline currently does not support:
```
{
"event": {
"body": {},
"method": "GET",
"principalId": "150efb8b-5e2d-4cdd-88a5-5e1c74d06861",
"stage": "dev",
"cognitoPoolClaims": {
"sub": ""
},
"enhancedAuthContext": {
"principalId": "150efb8b-5e2d-4cdd-88a5-5e1c74d06861",
"integrationLatency": "583",
"somekey": "xxxxx"
},
"headers": { ... },
"query": {},
"path": {},
"identity": { ... },
"stageVariables": {},
"requestPath": "/"
}
}
```
This PR adds the …
> feat: add authorizer enhanced context

- src/createVelocityContext.js
> Added support for AUTHORIZER env var in lambda integration (v5)

- README.md
- package.json
Just running `serverless` doesn't show plugins. You need to run it with `--verbose` to view plugins.
> [docs] Improve command to test installation

- tests/integration/python/python2/python2.test.js
In no python2 environment, it doesn't work.
> Fix broken python2 integration test

- src/lambda/handler-runner/docker-runner/DockerContainer.js
- tests/integration/docker/access-host/accessHost.test.js
- tests/integration/docker/access-host/serverless.yml
- tests/integration/docker/access-host/src/handler.js
fixes #858
- stop using host networking mode on linux
- add `host.docker.internal` DNS name  on linux to access host service from inside the container
> Add `host.docker.internal` DNS name to container on linux

- src/events/http/HttpServer.js
With this change the `string` type lambda responses will be stringified using `JSON.stringify` function.
This should fix the following issue https://github.com/dherault/serverless-offline/issues/702
> JSON stringify string responses

- src/ServerlessOffline.js
- src/events/schedule/Schedule.js
Fixes #878 by emulating the behavior of AWS Lambda as explained in the issue.
When serverless.yml has no input defined for the scheduled event payload, one is generated emulating the one you get from AWS.
The generated object looks like this:
```js
{
version: '0',
id: 'random-event-id',
account: 'random-account-id',
region: 'xxx' // actual region from serverless.yml
time: 'xxxx' // generated on every call via new Date().toISOString()
'detail-type': 'Scheduled Event',
detail: {},
source: 'aws.events'
}
```
> Provide default event payload for scheduled when "input" not specified in serverless.yml

- src/events/schedule/ScheduleEvent.js
Fix "TypeError (0 , _index.createUniqueId)(...) is not a function" when invoking scheduled events, see #886.
> Fix invalid call to createUniqueId in ScheduleEvent.js

- src/functionHelper.js
I discovered while working on [serverless-offline-sqs](https://github.com/CoorpAcademy/serverless-plugins/tree/master/packages/serverless-offline-sqs) environment handling,
that I had some issue when using a non js handler and overriding the config file.
`sls invoke` being called without forwarding the config file, and so in my case, the lambda not being found/configured.
Here is what would fix it IM. :)
(I had experiment it locally and that I solves my issue)
I had a look around the tests, and did found an obvious place to put it.
If you give me some it, I'll be happy to add them there.
Precision: I purposefully made this PR on the v5.x branch in the hope to have a patch release. =)
> Forward config overrides file to serverless when invoking proxy handler

- src/lambda/LambdaFunctionPool.js
I added calling `cleanup()` method of LambdaFunction to lambda function cleaner. It prevents zombie container of docker runner.
> Cleanup lambda function before delete

- CONTRIBUTING.md
Howdy folks! Thanks for all the work you do on this npm package! I'm in the middle of adding to it for my team's need with custom authorizers in AWS... but didn't realize until now that those changes belong on the [v5.x-release](https://github.com/dherault/serverless-offline/tree/v5.x-release) branch instead of master. I had already added to the CONTRIBUTING.md file on master for the new babel setup, so figured I'd offer it here since I have it.
> Add contrib doc for dev-local with serverless.yml vs package.json

- src/events/http/HttpServer.js
The _path property is set initially during the `createRoutes` call and is passed into `LambdaIntegrationEvent` function for every request. This results in the initial path as defined in the `serverless.yml` being used for every request.
Prior to **6.0.0-alpha.54**, the `event.path` property would reflect the current request path. eg `/graphql`
**6.0.0-alpha.56** appended the stage to the path, e.g. `event.path: /dev/graphql`
**6.0.0-alpha.61** removed the stage but the path that is defined in the `serverless.yml` is used for for every request, e.g. `event.path: /{any+}`
I think related to:
#870
#896
This commit may have implications on other features that I am not aware of, I'm relatively new to Lambda's and Serverless.
Edit: typo
> fix(http-server): change hapiHandler to use current request path

- src/config/supportedRuntimes.js
- tests/integration/docker/ruby/ruby2.7/dockerRuby2.7.test.js
- tests/integration/docker/ruby/ruby2.7/handler.rb
- tests/integration/docker/ruby/ruby2.7/serverless.yml
- tests/manual/ruby/serverless.yml
Support ruby2.7 runtime.
- https://aws.amazon.com/about-aws/whats-new/2020/02/aws-lambda-supports-ruby-2-7/?nc1=h_ls
- https://github.com/lambci/docker-lambda/releases/tag/ruby2.7
> Support ruby2.7

- src/ApiGateway.js
- src/__tests__/integration/offline.js
Requests to `resourceRoutes` created behind an API Gateway Proxy (i.e., running with `--resourceRoutes`) would fail due to hapi just exploding on the cookie validation.
This just rips off the strategy in #513 (specifically https://github.com/dherault/serverless-offline/commit/5d9a67a5c460e456e54e5be0967807fcfdee2064).
Much of the credit here goes to @cassiohub (@cassiohubner on GitLab).
> Also support `--disableCookieValidation` when we `_createResourceRoutes`.

- src/ServerlessOffline.js
This patch adds support for the new httpApi that aws offers
for reducing cost and latency in serverless applications. It
has been supported for a while in serverless, this just adds
support here to match.
The approach is pretty straightforward so far and may not include
all of the functionality that httpApi permits so far. Those will
come in later patches to this pull request.
> Adds support for httpApi

- src/events/http/HttpServer.js
- src/serverlessLog.js
Fixes an issue where the `event.path` would get truncated if no stage prepend was enabled. Also renables logging the stage path in table output.
Closes https://github.com/dherault/serverless-offline/issues/938
> fix: fixup no prepend stage changes

- README.md
I found this useful information for debugging. It was not immediately evident that this could be done by reading `aws lambda invoke help` since `--endpoint-url` is a general configuration for most aws commands.
> Add aws cli invoke instructions to readme

- src/ServerlessOffline.js
Check for the existence of a handler property before trying to have serverless-offline set up an event handler. It's possible to have mock integrations configured in API Gateway via serverless framework that have no handler and always return a static response. My team has and is using these in production, but serverless-offline cannot handle them right now.
This fix prevents serverless-offline from crashing, but it still warns `WARNING: Entry for my-function-without-handler@undefined could not be retrieved.`
I can provide a full example serverless.yml that triggers this bug if requested.
https://serverless.com/framework/docs/providers/aws/events/apigateway/#mock-integration
> Fix: serverless-offline crashes if a function definition does not have a handler

- src/events/http/HttpServer.js
- tests/old-unit/offline.test.js
__This should close https://github.com/dherault/serverless-offline/issues/974 by forward porting my v5 solution from https://github.com/dherault/serverless-offline/pull/863__.
Requests to `resourceRoutes` created behind an API Gateway Proxy (i.e., running with `--resourceRoutes`) would fail due to hapi just exploding on the cookie validation.
This just rips off the strategy in https://github.com/dherault/serverless-offline/pull/513 (specifically https://github.com/dherault/serverless-offline/commit/5d9a67a5c460e456e54e5be0967807fcfdee2064) and https://github.com/dherault/serverless-offline/pull/863
Much of the credit here goes to @cassiohub (@cassiohubner on GitLab).
> Also support `--disableCookieValidation` when we `createResourceRoutes`.

- package-lock.json
- package.json
- src/config/commandOptions.js
- src/config/defaultOptions.js
- src/lambda/LambdaFunctionPool.js
- src/lambda/handler-runner/python-runner/PythonRunner.js
- src/lambda/handler-runner/python-runner/invoke.py
The current implementation for Python handlers spawns a new child process on each endpoint invocation, which then has to re-do all of the Python imports/bootstrapping, which can be quite slow for large projects.
This PR keeps a process around for each handler function that it reuses on each new invocation, making it much more performant.
> Reuse Python handler processes for performance.

- README.md
- src/config/commandOptions.js
- src/config/defaultOptions.js
- src/events/http/HttpServer.js
In v6 of `serverless-offline`, the `prefix` option got removed. I'm not aware of the context behind this, but it seems like a few people would love to have this functionality back, and @dherault seems open to this idea.
https://github.com/dherault/serverless-offline/issues/929
> feat(prefixes): Bring back prefix option

- src/lambda/handler-runner/python-runner/invoke.py
Fixes #989
When running Python function on Windows OS, invoke.py cannot import handler module because it doesn't convert path separator of Windows OS "\" to ".".
So, I fixed that using os.sep instead of literal "/".
> Fix:#989 ModuleNotFoundError occur when running Python function on Windows OS

- package-lock.json
- src/events/http/HttpServer.js
- src/utils/generateHapiPath.js
- src/utils/index.js
In my previous [PR](https://github.com/dherault/serverless-offline/pull/988) I noticed there was some duplicate logic for generating paths in `createRoutes` and `createResourceRoutes`.
Have extracted this code to a utility so any future updates can happen in one place.
> refactor: Extract util for generating hapiPath

- jest.config.units.js
- package-lock.json
- package.json
For the purposes of faster development, this PR adds an npm script (`npm run test:unit`) for running only unit tests, and without `npm install`.
> NPM script for running only unit tests

- src/utils/generateHapiPath.js
[Issue #999](https://github.com/dherault/serverless-offline/issues/999) discovered that star routes are not being handled correctly, since no path property is present. Defaulting the path to an empty string allows the pathing to be applied properly.
> fix: Handle star routes

- src/events/http/createAuthScheme.js
- src/events/http/lambda-events/LambdaProxyIntegrationEvent.js
- tests/integration/handler/handler.js
- tests/integration/handler/handlerPayload.test.js
- tests/integration/handler/serverless.yml
Fixes https://github.com/dherault/serverless-offline/issues/917
I still need to write tests for this fix.
I must say, the development experience to contribute to this project for the first time is quite poor. 
The main issue is I could not run tests reliably in my machine:
- every single time I want to run tests, npm installs every 'scenario' dependencies
- I cannot run unit tests separately, only the whole project with many integration tests
- I'm not sure where to add tests, considering unit tests are in a folder `old-unit`. I'm not confident in adding code to something with `old` in its name
- Some random tests break by timeout
- Husky runs tests on every push
In my opinion, tests should be easy to run locally, but not enforced to be ran on every push. Travis CI already does this tests …
> fix: resourcePath in authorizers should contain wildcards

- src/events/http/HttpServer.js
This PR addresses [issue #984](https://github.com/dherault/serverless-offline/issues/984). Currently when an `origin` header is being set, a bunch of other default headers are being set too.
These default headers override any headers that may want to be set explicitly in the lambda. This PR fixes that.
> fix: Allow explicitly setting headers within lambda

- jest.config.js
- package.json
Added an `npm` script to run `jest` with `--watch` to speed up local testing. Skips the install script as this is usually unnecessary when just writing or updating tests.
> refactor: Script for running tests with --watch

- CONTRIBUTING.md
- package.json
Update the contributing file with updates about the new test scripts.
- Updated CONTRIBUTING.md
- Added a `format` command for automatically fixing linting errors
> Contributing updates

- src/lambda/LambdaFunction.js
- src/utils/resolveJoins.js
Currently, `Fn::Join` is not being resolved correctly in environment variables. This PR uses javascript's `Array.join` to correctly resolve such values.
> feat: Resolve Fn::Join in environment variables 

- src/events/http/HttpServer.js
- src/events/http/parseResources.js
- src/utils/generateHapiPath.js
Fixes: #1016 
I don't think we still need this path.replace, i could not find any case for it(hopefully someone more familiar with the code can shine some light on it). Especially since in generateHapiPath.js, where the resulting path is used, we expect this '+' to still be there.
> fix greedy path for proxy

- src/events/http/HttpServer.js
When we send a request to a proxy we have this kind of output
> Fix Api Gateway Proxy logs

- package-lock.json
- package.json
- src/events/http/HttpServer.js
- src/events/http/payloadSchemaValidator.js
- tests/integration/handler/handler.js
- tests/integration/handler/handlerPayload.test.js
- tests/integration/handler/serverless.yml
Implementing request body validation from schema #734 
serverless: serverless/serverless#5956
Serverless doc explaining JSON schema validation:
https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#request-schema-validators
> JSON schema validation for http request body

- src/events/http/createJWTAuthScheme.js
- tests/integration/jwt-authorizer/jwt-authorizer.test.js
[The `aud` claim in a JWT token can be an list](https://stackoverflow.com/a/41237822), in which case, validation should pass if one of the values matches one of the values configured for the authoriser. 
For example, see [Auth0 access tokens](https://auth0.com/docs/tokens#access-tokens).
> JWT token contains multiple audience values (eg, Auth0)

- README.md
- src/config/commandOptions.js
- src/config/defaultOptions.js
- src/events/websocket/WebSocketClients.js
- src/events/websocket/lambda-events/WebSocketRequestContext.js
This PR add WebSocket idle & hard timeouts support. This is configurable, in order to be able to test timeout behaviour without having to wait for 2 hours 😄 
Also fixing connectedAt request context attribute.
I didn't add test because there is no tests currently so it's a lot of work to add test for this.(I found https://github.com/dherault/serverless-offline/pull/814 but looks like it won't be merged)
> Support WebSocket timeouts limits & fix connectedAt context attribute

- src/ServerlessOffline.js
Fixing a regression of a fix for bug raised in a #832 issue.
> Regression: randomly generated API key is not displayed if no API key is defined

- src/utils/resolveJoins.js
- tests/endToEnd/environmentVariables/environmentVariables.test.js
- tests/endToEnd/environmentVariables/handler.js
- tests/endToEnd/environmentVariables/serverless.yml
Suggested fix for https://github.com/dherault/serverless-offline/issues/1048 - tested locally and it works for me.
I also added a test suite for env var handling
Fixes the following exception:
```
Debug: internal, implementation, error
TypeError: Cannot read property 'Fn::Join' of undefined
at /Users/alexhayton/personal/stablemaster/lambda/node_modules/serverless-offline/dist/utils/resolveJoins.js:17:28
at Array.forEach (<anonymous>)
at resolveJoins (/Users/alexhayton/personal/stablemaster/lambda/node_modules/serverless-offline/dist/utils/resolveJoins.js:15:28)
at new LambdaFunction (/Users/alexhayton/personal/stablemaster/lambda/node_modules/serverless-offline/dist/lambda/LambdaFunction.js:154:56)
at LambdaFunctionPool.get (/Users/alexhayton/personal/stablemaster/lambda/node_modules/serve …
```
> Handle undefined environment variables in resolveJoins

- README.md
- package.json
- src/lambda/HttpServer.js
- src/lambda/Lambda.js
- src/lambda/routes/invocations/InvocationsController.js
- src/lambda/routes/invocations/invocationsRoute.js
- src/main.js
- tests/integration/lambda-invoke/lambdaInvoke.test.js
- tests/integration/lambda-invoke/lambdaInvokeHandler.js
- tests/integration/lambda-invoke/serverless.yml
* Improves the understanding of the offline direct lambda invocations and how to use them
* Handles two common error scenarios gracefully and with responses matching AWS production Lambda endpoints:
1. Function does not exist
2. Function throws an unhandled error
Should help solve:  #1015, #987, #982, #969, #843, #761
_All issues stem from not knowing what routes are active and can be triggered by either `aws-sdk`, `aws-cli`, or manually via a REST client_
Previously if there was a function name mis-match (usually because a custom naming scheme is being used), the error message was not helpful because the error would only be triggered when `serverless-offline` would try to invoke the non-existent function, rather than when it tries to find the function.
Additionally, there was a 'TODO' on …
> Improved lambda invoke

- README.md
Fix #1084 
Remove (possibly) unintended big font for a paragraph in docs
> [Docs] Fix #1084

- package-lock.json
- package.json
- update sub-dependency `bl` using resolution for critical cve
> chore: update sub-dependency `bl` using resolution for critical cve

- src/events/http/lambda-events/LambdaProxyIntegrationEventV2.js
This PR fixes the JWT authorizer payload for the payload v2. It also removes the `principalId `field from the payload, since this doesn't seem to exist on the v2 payload. (_Please correct me if this is wrong._)
Previously, the claims and scopes were nested according to the v1 format, which breaks functions that expect the v2 payload.
This was tested manually on my machine using a JWT authorizer with an AWS Cognito User Pool as the issuer and a TS function.
> Fix jwt authorizers payload v2

- src/events/http/createJWTAuthScheme.js
- tests/integration/jwt-authorizer/jwt-authorizer.test.js
Auth0, for example, can send aud: ["<audience1>", "<audience2>"] in it's token. It also looks like it's possible to configure multiple or single acceptable audiences in the serverless.yml. This PR lifts both sets of audiences into an array which are then checked for an overlap.
I originally submitted this change as https://github.com/dherault/serverless-offline/pull/1060 which was closed in favour of the similar https://github.com/dherault/serverless-offline/pull/1070. Now that I've had chance to use the version that includes that change, I still see the same error that motivated my original PR.  I think my change is still needed.
Tests now exist for string-based audiences, array-based audiences containing a single element and array-based audiences of length > 1.
> Jwt audience validation

- src/events/http/lambda-events/LambdaProxyIntegrationEvent.js
Change LambdaProxyIntegrationEvent returned resource to use non-stagePrepended URL from instance #path intead of route.path.
When running serverless-offline locally, the LambdaProxyIntegrationEvent uses the route.path to define the event.resource instead of this.#path. When using stages prepended to URLs to keep in step with a multi-environment local development setup (i.e. multiple environments tested with Postman), it is desirable to have the stage prepend the endpoint URL, but not desirable for the stage to mutate the event.resource where router / controller logic is determined.
Fixes: https://github.com/dherault/serverless-offline/issues/1029
Ran AWS Lambdas locally with URLs prepended by Stage with Postman.
> Lambda-Event-Path-and-Resource-Sync

- src/events/http/lambda-events/LambdaProxyIntegrationEvent.js
See: 
https://github.com/dherault/serverless-offline/pull/1137
https://github.com/dherault/serverless-offline/pull/1137#issuecomment-742603299
That PR broke path parameters.
This PR fixes that issue and still sovles the need to remove stage from path for event.resource
> Get event.resource by removing stage from route.path

- README.md
- src/events/http/lambda-events/LambdaProxyIntegrationEvent.js
Adds the ApiKeyId to the identity object in the requestContext of the LambdaProxyIntegrationEvent
When testing locally it sometimes is needed to read out the apiKeyId instead of the apiKey
#1035 
I npm link'ed this branch in my local environment and verified the apiKeyId was available in the event.
There seems to be no unit test that covers the contents the identity object, except for a file in the folder called "old-unit". Please let me know if adding an additional expect there is appreciated.
> Fix #1035 - Add apiKeyId to identity information

- src/lambda/LambdaFunction.js
AWS has updated billing to the nearest 1ms instead of 100ms as per https://aws.amazon.com/about-aws/whats-new/2020/12/aws-lambda-changes-duration-billing-granularity-from-100ms-to-1ms/ 
AWS has updated billing to nearest ms, so the estimated billed duration should reflect the change
n/a
> Update billing to nearest ms

- src/config/supportedRuntimes.js
- src/lambda/handler-runner/HandlerRunner.js
AWS Lambda now supports nodejs14.x. Updated the package to support this version.
Without this support, an error is thrown when trying to run serverless offline on projects that use node 14.
I made changes to the config file in `serverless-offline`. Then used `yarn link` to link the local package and used it in one of my nodejs 14 serverless projects. It did not throw an error after the changes and ran the code as expected.
> feature: add support for nodejs14.x

- src/events/http/createJWTAuthScheme.js
Using .includes within a safe array variable `validAudiences` rather than unsafe includes call on `jwtOptions.audience`
I replaced the call of includes to an existing safe variable array `validAudiences`, because the old code `jwtOptions.audience.includes` throws errors when the type of `jwtOptions.audience` is not an array.
It fixes an open issue #1078
It's a very very very small change in the code, also I ran `npm run test:unit` and it passes.
> Use .includes within a safe array variable "validAudiences"

- src/config/commandOptions.js
Add types to CLI command options arguments
Serverless has introduced a mandatory type definition for CLI arguments
https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
I did not test it, just used common sense to define the types, it definitely needs review from someone else.
The framework also allows for a `default` argument value, which I'm not really sure it's useful at this time.
> refactor: add types to cli command options

- src/ServerlessOffline.js
- src/events/http/HttpServer.js
- src/events/http/lambda-events/LambdaProxyIntegrationEvent.js
- src/events/http/lambda-events/LambdaProxyIntegrationEventV2.js
- tests/integration/jwt-authorizer/jwt-authorizer.test.js
Fixes #1118 but also addresses other issues found with `httpApi` events:
* Default payload format is now `2.0` (NB: also implemented by #1126 which does not include required fixes to 2.0 event payloads)
* Support for `$default` route
* Support for `$default` stage (Serverless always deploys to `$default` stage which should never be prepended to URL)
* ~Support for CORS configuration which is provided in `provider.httpApi`~ (reverted in favor of #1153)
* Fix `LambdaProxyIntegrationEvent.resource` which should be the route key (for `httpApi` events only)
* Fix `LambdaProxyIntegrationEventV2.routeKey` which should be the route key
* Fix `LambdaProxyIntegrationEventV2.rawPath` which should be obtained from the requested URL (not the route)
* Optimize …
> Support for HttpApi $default route, $default stage and 2.0 payloads

- src/lambda/handler-runner/ruby-runner/RubyRunner.js
This fix allows stdout to be logged to the console, allowing Ruby output operations like `logger.info`, `puts` and `p` to materialize.
Emulates the way `sls invoke local --function ...` logs such statements.
The use of `logger` is [officially supported](https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/sample-apps/blank-ruby/function/lambda_function.rb) by AWS in Lambda, and should produce the same result when running offline. It is also useful to be able to print to console for debugging purposes. The implementation of the Python runner [does a similar thing](https://github.com/dherault/serverless-offline/blob/b55c846a0f0cdae14b320f50c1f6c8e9acb80c70/src/lambda/handler-runner/python-runner/PythonRunner.js).
Resolves https://github.com/dherault/serverless-offline/issues/1206 …
> Fix: Log ruby stdout to console

- tests/integration/httpApi-cors/httpApi-cors.test.js
Fix HTTP CORS integration tests to call proper PATH after changes introduced in: https://github.com/dherault/serverless-offline/pull/1175
Failing tests on master, visible e.g. here: https://github.com/dherault/serverless-offline/runs/2391560450?check_suite_focus=true
Automated tests
> test: Fix http cors integration test URL paths

- src/lambda/handler-runner/docker-runner/DockerContainer.js
Add Handling for IPv6 line of [`docker port`](https://docs.docker.com/engine/reference/commandline/port/) output.
Starting with docker engine v20.10.6, `docker port` outputs not only IPv4 mappings but also IPv6 mappings.
e.g.:
```console
$ docker port container
9001/tcp -> 0.0.0.0:49153
9001/tcp -> :::49153
```
https://docs.docker.com/engine/release-notes/#20106
> Fix implicit IPv6 port-mappings not included in API response. Before docker 20.10, published ports were accessible through both IPv4 and IPv6 by default, but the API only included information about the IPv4 (0.0.0.0) mapping moby/moby#42205
The container port parsing has been broken by the IPv6 mapping line.
Failing tests on master, visible e.g. here: https://github.com/dherault/serverless-offline/runs/2438945825?check_suite_focu …
> Fix docker engine v20.10.6 compatibility

- README.md
- src/config/commandOptions.js
- src/config/defaultOptions.js
- src/events/http/HttpServer.js
- src/utils/generateHapiPath.js
- tests/endToEnd/trailingSlash/handler.js
- tests/endToEnd/trailingSlash/serverless.yml
- tests/endToEnd/trailingSlash/trailingSlash.test.js
Add `--noStripTrailingSlashInUrl` option passing ending slash to Lambda event.
We have Lambda responding on HTTP event having `/{any+}` path. Currently it is not possible to receive trailing slash in the requested event path. Both `/dev/hello` and `/dev/hello/` are sent to Lambda as `/dev/hello`.
Extra option allows event to be set with a trailing slash and allows request to be sent to Lambda with a trailing slash.
> Add '--noStripTrailingSlashInUrl' option

- README.md
- package.json
- src/utils/__tests__/splitHandlerPathAndName.test.js
- src/utils/splitHandlerPathAndName.js
This enhancement adds support for Ruby handlers that have namespace resolution operators (`::`) in their path definition, e.g. `handler: 'src/lambdas/examples/hello.Hello::Handler.process'`, etc. This was officially mentioned in the AWS documentation (see below). Logic was preserved for existing scenarios (without `::`) to reduce the risk of regression.
Without this enhancement, the following error message is triggered when the handler is invoked
```
offline: Failure: Command failed with exit code 1: ruby /PATH_TO_PROJECT/node_modules/serverless-offline/dist/lambda/handler-runner/ruby-runner/invoke.rb src/functions/source.LambdaFunctions::Handler process
~/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- …
```
> feat: Support Ruby handlers with `::` in path definition

- src/lambda/__tests__/LambdaFunction.test.js
- src/lambda/handler-runner/in-process-runner/InProcessRunner.js
Remove a multiplication of `this.#timeout` by 1000
The value returned by `context.getRemainingTimeMillis()` was 1000 times greater than expected, ie. 900000000 not 900000.
It has already been multiplied by 1000 at
https://github.com/dherault/serverless-offline/blob/91592d3b5bc51fb0975862dcbd06f66be80a7f51/src/lambda/LambdaFunction.js#L67 so after multiplying it again at https://github.com/dherault/serverless-offline/blob/1454da7dcff5f48da9f19135cb18590b22e29cc2/src/lambda/handler-runner/in-process-runner/InProcessRunner.js#L125 it was 1000 times greater than expected.
The `getRemainingTimeMillis` (timeout) check in the `LambdaFunction` test was incorrectly checking that the function returns a value greater than the original timeout instead of less than the original timeout.
After fixing …
> fix: Remove multiplication of `this.#timeout` by 1000

- src/lambda/handler-runner/child-process-runner/ChildProcessRunner.js
When using useChildProcesses: true, child processes are killed when they finish their execution
#1105 
In the latest version of serverless-offline, using the v12.20.1 version of node and using the task manager, I was able to verify that when the invocation of the function finishes it closes it correctly
I wanted to do unit tests for this but I really don't know what they would be like
> fix: Child processes are cleaned up when `useChildProcesses` is used

- .github/workflows/CI.yml
- package-lock.json
- package.json
- tests/integration/handler/handlerPayload.test.js
- tests/old-unit/offline.test.js
This updates hapi versions to the latest to fix an issue where requests will hang on node 16. See https://github.com/hapijs/hapi/pull/4225 for the fix in hapi.
However the latest version of hapi isn't compatible with node 10 so this requires dropping support (see https://hapi.dev/resources/changelog/).
Support node 16.
Fixes #1229
Tested by running a large serverless app with this fix on node 16. Also checked the hapi changelog to make sure no breaking changes would affect this. Added node 16  to CI.
N/A
> feat: Update `hapi` version to support Node 16 and drop Node 10

- src/config/supportedRuntimes.js
- src/lambda/handler-runner/HandlerRunner.js
Add support for Python 3.9 runtime
Motivation was to get serverless-offline to support latest stable Python version (3.9).
Fixes issue: https://github.com/dherault/serverless-offline/issues/1266
I cloned [serverless-offline](https://github.com/dherault/serverless-offline) repo, built it, and included it in my Serverless Framework project. Before my patch, when trying to use Python 3.9 I got error:
```
offline: Warning: found unsupported runtime 'python3.9' for function 'foo'
offline: Failure: Unsupported runtime
```
After this change there was no error and everything worked as expected.
> feat: Add support for Python 3.9 runtime

- package.json
- src/lambda/__tests__/fixtures/Lambda/LambdaFunctionThatReturnsJSONObject.fixture.js
- src/lambda/__tests__/fixtures/Lambda/LambdaFunctionThatReturnsNativeString.fixture.js
- src/lambda/__tests__/fixtures/lambdaFunction.fixture.js
- src/lambda/__tests__/routes/invocations/InvocationsController.test.js
- src/lambda/routes/invocations/InvocationsController.js
Wrap Lambda Invocation Responses that are native strings with `""`
Using this library with [`serverless-step-functions`](https://github.com/serverless-operations/serverless-step-functions) and [AWS step functions local](https://docs.aws.amazon.com/step-functions/latest/dg/sfn-local-docker.html) we noticed that Lambda Invocations that returns a single native string threw an error on JSON parsing from the Step Functions Local App. After some investigation and feedback with the AWS support team, we noticed that AWS SAM and Serverless Offline responses for Lambda Invocations when returning a single string is a bit different 
Serverless Offline Lambda Endpoint
```js
=== { StatusCode: 200, Payload: '46585b35-b4fa-4db8-968d-5deef4ba2858' }
```
SAM CLI Lambda Endpoint:
```js
=== { StatusCode: …
```
> fix: Wrap native string responses from lambda invocation endpoint

- src/ServerlessOffline.js
Currently if the plugin would be run with Framework v3 pre-release, a warning will be shown about incompatibility.
As pre-releases cannot be targetted with elastic semver ranges, ideally they should not be validated in any case
> Do not validate compatibility against serverless pre-releases

- tests/integration/_testHelpers/setupTeardown.js
When underlying `sls offline` command fails, so far tests did nothing just waited for timeout. This patch ensures we crash and print output of failed command
Additionally added option to unconditionally print output of underlying `sls offline` command. It helps diagnosing the issues
> Improve tests handling

- CHANGELOG.md
- commitlint.config.js
- package.json
It'll make changelog notes generation easier, and we already practise conventional commits here
> Setup auto CHANGELOG generation

- src/ServerlessOffline.js
This PR adds support for getting the payload version for `httpApi` functions from the function definition (ie overriding the `provider` level).
According to the [serverless docs](https://www.serverless.com/framework/docs/providers/aws/events/http-api#event--payload-format), you can specify `httpApi.payload` at either the service or function level. However, serverless-offline was ignoring the value set at the function level. This PR fixes that.
I've tested this in my current project.
> Support httpApi payload override on handler

- README.md
- package.json
- src/ServerlessOffline.js
- src/config/commandOptions.js
- src/config/defaultOptions.js
* Add support for using `--disableScheduledEvents` from the command line to force all scheduled events to become disabled.  Resolves #1123.
* Also included a fix for husky pre-commit lint error I was receiving while trying to create this PR by moving the :
```
> serverless-offline@6.8.0 lint /serverless-offline
> eslint .
/serverless-offline/src/lambda/LambdaFunction.js
39:3  error  'status' is not defined  no-undef
✖ 1 problem (1 error, 0 warnings)
```
During development some of us are wanting to disable all scheduled events from being scheduled without also needing to modify our `serverless.yml`.
Tested out a `serverless.yml` configuration with a scheduled event configuration:
```
testEvent:
handler: src/index.testEvent
events:
- schedule:
enabled: true
rate: rate(1 minute)
testEvent2: …
```
> Add command line option for disabling scheduled events.

- src/events/http/HttpServer.js
- src/events/http/lambda-events/LambdaProxyIntegrationEvent.js
- src/events/http/lambda-events/LambdaProxyIntegrationEventV2.js
- tests/integration/lambda-integration/handler.js
- tests/integration/lambda-integration/lambdaIntegration.test.js
- tests/integration/lambda-integration/serverless.yml
- tests/old-unit/LambdaProxyIntegrationEvent.test.js
AWS ApiGateway defines a `operationId` value for each http event. This value is available in the running Lambda in the `event.requestContext.operationName` property. This property value is very helpful if validating requests against an OpenApi spec.
This PR takes the `operationId` value and makes it available in the `event` model for both `LambdaProxyIntegrationEvent` and `LambdaProxyIntegrationEventV2`
This supplies a value that is available when running the Serverless deployment in the AWS environment, but until now, not available in the offline environment.
I have added unit and integration tests. We have also been using this code internally for the past year.
> feat: Add `httpEvent.operationId` to the request context

- src/lambda/routes/invocations/invocationsRoute.js
If ```invokeResults.Payload === 0```, then it gets replaced by empty string ```''```, which causes buggy behavior in many cases.
> Example case: 
> We have a lambda that returns a number of upvotes for a post. 
> So, when it returns ```0```, then HTTP response contains ```''``` (empty string) instead.
Manual testing (nothing should be broken).
[Screenshot](https://take.ms/4CLW5)
> [Bug] Fix issue with incorrect 0 -> '' conversion in HTTP responses

- src/lambda/handler-runner/ruby-runner/RubyRunner.js
This PR prevents from `stdout` from being replaced with `stderr` in responses from Ruby handlers.
When I run my Ruby handler (which uses [serverless-rack](https://github.com/logandk/serverless-rack) to run a Sinatra application, I noticed that whenever I add a logging statement (such as `puts` or `logger.info`), the response from my handler no longer shows in my browser. Instead, I get the logs in my browser (in addition to the console).
Same thing happens when there's an uncaught error. My app's error page is bypassed, and instead my error logs are printed to the browser.
I found out that this is because Rack's error stream is stderr (as it should be), and these lines in this project:
https://github.com/dherault/serverless-offline/blob/febfe77d470b2e5e4fbfe5243b265d6a27fb84f3/src/lambda/h …
> fix: Don't override Ruby `stdout` with `stderr`

- src/ServerlessOffline.js
Based on previous discussions with @dl748 around #1090, I've implemented this proof of concept for how `serverless-offline` might allow other plugins to trigger a lambda cleanup for hot reloading.
Even without integration directly within something like `serverless-webpack`, this enables a custom plugin to hook the relevant event and then invoke the `offline:functionsUpdated` command that this PR adds ([example](https://gist.github.com/kelchm/dab3b255fe44ed8cbb89088a963c0e19)).
Like with #1090, this still relies on `useWorkerThreads: true` and `allowCache: true` for this to actually work as expected. I'm also not really happy with the naming conventions here, please feel free to share any ideas if you have them.
> POC for externally triggering cleanup of lambda functions

- src/lambda/LambdaFunction.js
Fixing AWS env vars to make work with Layers
Without `LD_LIBRARY_PATH` correct value, layers bin doesn't work correctly. More details about this variables can read [here](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime)
I found this bug running this [layer](https://github.com/rpidanny/gm-lambda-layer). 
To simulate the problem, create a lambda function with this layer and set this [code](https://github.com/rpidanny/gm-lambda-layer/blob/master/test/index.js), when the code is called an error is raised. Entering in docker container, is possible to see that 
`LD_LIBRARY_PATH` doesn't have `/opt/lib` value.
After fixing the env value, this layer work as expected.
> Fixing AWS env vars

- src/lambda/handler-runner/in-process-runner/InProcessRunner.js
Adding node_modules check to orphan unloading.
if the module in question included a binary plugin, this can cause problems when reloading. We should probably never unload a node_modules package and require the developer to restart if they update or change them. This will force any code outside of node_modules to reload which I think is acceptable, however, if the developer has their OWN binary plugin, this could still be an issue.
Included a binary module into the handler that is only used there and called the handler more than once
> Never remove cached node_modules or binary modules

- src/events/http/lambda-events/LambdaProxyIntegrationEventV2.js
This PR makes `serverless-offline`'s handling of multiple cookies with the same name reflect that of API Gateway.
The existing implementation merges cookies with the same name into a single cookie with a comma separated value, i.e. given cookies `foo=bar` & `foo=baz`, `APIGatewayProxyEventV2.cookies` resolves to `foo=bar,baz`. 
After the change, cookies with the same name are kept separate, i.e. given cookies `foo=bar` & `foo=baz`, `APIGatewayProxyEventV2.cookies` resolves to `foo=bar,foo=baz` (as API Gateway behaves). 
The current implementation is not representative.
I would be quite happy to add automated tests but I could find no existing precedent for testing code in this class. Please feel free to suggest an automated testing strategy if you would like me to employ one.
I tested my …
> Handle multiple cookies with the same name in the same way API Gateway does.

- src/events/http/HttpServer.js
- src/events/http/lambda-events/LambdaProxyIntegrationEvent.js
- src/events/http/lambda-events/LambdaProxyIntegrationEventV2.js
An error occurred that the binary could not be passed normally.
serverless-offline is currently unable to handle binaries normally.
1. ``rawPayload`` has the same value as ``payload`` because ``rawPayload`` has been allocated while ``payload`` has already been converted to ``.toString()``. Changed the order in which ``payload`` is converted after assigning ``rawPayload``.
2. Since the ``body`` (or ``payload``) is converted by ``.toString()``, the unconditional type is String. Changed to use ``rawPayload`` only if ``rawPayload`` is not a String.
By applying the unit test through ``npm test:unit`` and the serverless project under development, we confirmed that the binary was inserted normally.
> Fixed the problem that the binary is not uploaded normally.

- src/events/http/authValidateContext.js
- src/events/http/createAuthScheme.js
- tests/integration/authorizer/authorizer.js
- tests/integration/authorizer/authorizer.test.js
- tests/integration/authorizer/handler.js
- tests/integration/authorizer/serverless.yml
When successfully returning a policy from an Authorizer function, if the returned policy contains a context object containing values that are not of type `string`, `number`, or `boolean`, it will cause the endpoint to return 500, with the header: `x-amzn-ErrorType: AuthorizerConfigurationException`. In addition, `string`, `number`, and `boolean` values returned in the authorizer context are all coerced to string values when supplied to the downstream method implementation lambda.
None of this behavior is currently accounted for in the serverless-offline authorizer handling logic. This change fixes that issue, and makes serverless-offline authorizers behave near exactly like those of ApiGateway.
This change helps prevent developers from returning invalid types of authorizer contexts that …
> Validate authorizer context response to better mimic API Gateway (resubmit)

- src/events/http/lambda-events/LambdaIntegrationEvent.js
Added support for the AUTHORIZER env variable for LambdaIntegration (non-proxy) http requests 
The `AUTHORIZER` env variable was not working for LambdaIntegration http requests. I just added support for it.
This resolves #816 
I've run the unit tests. Full test run fails even on `master` in my computer.
> Add support for the AUTHORIZER env variable for LambdaIntegration

- tests/old-unit/offline.test.js
@dherault I believe the cause of the test failures are originated in the non-deterministic dependency installations.
this PR skips 2 failing tests. those should be fixed once the issue has been found.
> test: temporary skip tests

- src/config/supportedRuntimes.js
`serverless@3.17.0` finally landed with `nodejs16.x` support. This PR adds support for `serverless-offline`
> Add support for nodejs16.x

- src/events/schedule/Schedule.js
Simply enable the cron support that was disabled. It works, why not use it?
If there is an edge case it doesn't work for, then let's create an issue for it,
and i will gladly fix that.
In any case, for what is essentially a mocked dev environment, it's better to be able to
work for 90% of the use cases than none of them, and so far i haven't
been able to find any problems with it in my local development.
Need to test lambda functions w/ cron schedules
Please see issue: https://github.com/dherault/serverless-offline/issues/1044
Was able to successfully run cron schedules locally
> Enable support for cron schedules

- src/ServerlessOffline.js
- tests/endToEnd/starRoutesWithProperties/handler.js
- tests/endToEnd/starRoutesWithProperties/serverless.yml
- tests/endToEnd/starRoutesWithProperties/starRoutes.test.js
Allow the httpApi event to catch all the requests when specifying the path, method and other properties.
Currently, the only way to catch all requests in an httpApi event is to define it in-line:
```
functions:
hello:
handler: handler.hello
events:
- httpApi: '*'
```
But when trying to add properties, it's necessary to include the path (AWS requirements) and the method, such as:
```
functions:
hello:
handler: handler.hello
events:
- httpApi:
path: '*'
method: '*'
authorizer:
type: request
name: auth
```
serverless-offline fails to consider this route as the $default and will serve the 404 payload rather than route the request to the handler.
Automated tests have been added
> Support catch-all routes with method and path properties

- src/events/authValidateContext.js
- src/events/http/createAuthScheme.js
- src/events/websocket/WebSocketClients.js
- src/events/websocket/WebSocketServer.js
- tests/integration/websocket-authorizer/authorizer.js
- tests/integration/websocket-authorizer/handler.js
Move authorizer and identity data to requestContext in order to follow lambda proxy specs.
This pull request fix a wrong identity and authorizer informations contained in the lambda event instead of requestContext object
Relates to #1379
This fix a wrong behaviour for lambda and websocket authorizers.
Authorizer and identity data should be inside requestContext object when used with lambda proxy (like serverless-offline does)
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-lambda-authorizer-output.html
https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html
In particular a reference to:
```
For the Lambda proxy integration, API Gateway passes the context object from a Lambda authorizer directly to the backend Lambda …
```
> Fix websocket authorizers data located in wrong place

- src/utils/getHttpApiCorsConfig.js
Reduces log level of CORS policy, so there's not a warning log for every request to an endpoint that has CORS enabled.
Reduces noise in logs. Users can still find out this information if they want by tweaking their log settings.
Also see #1335
Reviewed the log levels in Serverless, and how the logging framework works there.
> Reduce log level of CORS settings

- src/events/http/HttpServer.js
- src/events/http/createAuthScheme.js
- src/events/http/lambda-events/LambdaIntegrationEvent.js
- src/events/http/lambda-events/LambdaProxyIntegrationEvent.js
- src/events/http/lambda-events/LambdaProxyIntegrationEventV2.js
- src/events/http/lambda-events/VelocityContext.js
- src/events/http/lambda-events/renderVelocityTemplateObject.js
- src/events/websocket/WebSocketClients.js
- src/events/websocket/WebSocketServer.js
- src/lambda/handler-runner/docker-runner/DockerContainer.js
- src/lambda/handler-runner/go-runner/GoRunner.js
- src/lambda/handler-runner/in-process-runner/InProcessRunner.js
- src/lambda/handler-runner/java-runner/JavaRunner.js
- src/lambda/handler-runner/python-runner/PythonRunner.js
- src/lambda/handler-runner/ruby-runner/RubyRunner.js
- src/utils/checkDockerDaemon.js
- src/utils/checkGoVersion.js
- src/utils/detectExecutable.js
- tests/_setupTeardown/npmInstall.js
> fix: remove catch binding

- src/events/websocket/WebSocketClients.js
- tests/integration/websocket-authorizer/src/authorizer.js
- tests/integration/websocket-authorizer/websocket-authorizer.test.js
- Fixes #1471
- The policy's context should be *optional*, but the code crashed if the context wasn't provided
- Followed a model similar to createAuthScheme where the context is properly checked for existence before being validated and used
- Add a test to verify the websocket authorizer works when the policy doesn't contain a context. This test fails with the existing code.
- Un-skipped the tests so they're actually run and verified the test now passes.
Policy context should be optional, and I was getting mysterious 500s by not providing it in a websocket authorizer.
I added a test to ensure websocket authorizers run properly without a policy context.
> fix: don't require context (#1471)

- src/lambda/handler-runner/in-process-runner/clearModule.js
Modified the regexes that determine whether modules can be unloaded to be Windows-friendly
See #1461 
Tested locally
> fix: serverless-offline v8.6 and later unloads all modules when running on Windows, breaking plugins

- src/events/http/HttpServer.js
Fixes a bug where node.js process fails to exit even though `ServerlessOffline.stop` was called.
Upgrading to `v9` I noticed my node.js process was no longer exiting cleanly during integration tests.
After some debugging I found that the reason is that in `v9`, `process.stdin.addListener` is not conditional anymore in `HttpServer`.
This leaves the `process.stdin` handle open, and prevents the process from exiting.
The fix is to add a `process.stdin.pause()` call to the `stop` function of `HttpServer`.
More info:
https://stackoverflow.com/questions/33831978/unknown-method-process-openstdin
I tested this locally and it fixed my issue, but since I didn't find relevant tests to this feature in the test-suite I didn't add any regression tests...
> fix: Cleanly exit node process

- src/lambda/handler-runner/worker-thread-runner/workerThreadHelper.js
In worker-runner `timeout` value was `NaN` because the timeout is passed via `workerData` not `message`.
https://github.com/dherault/serverless-offline/blob/master/src/lambda/handler-runner/worker-thread-runner/WorkerThreadRunner.js#L16-L25
Using `context.getRemainingTimeInMillis()` always returns `0`
Tested locally on a project
> fix: worker-runner timout option

- src/events/schedule/Schedule.js
This pull request prevents logging `undefined` if the `input` key is undefined.
Before and after:
`Scheduling [upload] cron: [*/1 * * * *] input: undefined`
`Scheduling [upload] cron: [*/1 * * * *]`
Running `sls offline`.
> fix: Prevent logging `undefined`  for event schedule

- src/lambda/handler-runner/child-process-runner/ChildProcessRunner.js
- tests/lambda-run-mode/child-processes/instances/in-process-instances.test.js
- tests/lambda-run-mode/child-processes/instances/serverless.yml
- tests/lambda-run-mode/child-processes/instances/src/handler.js
- tests/lambda-run-mode/child-processes/instances/src/package.json
fixes: https://github.com/dherault/serverless-offline/issues/1526
> fix: child processes run mode

- src/events/http/HttpServer.js
- tests/integration/lambda-integration/lambdaIntegration.test.js
- tests/integration/lambda-integration/serverless.yml
- tests/integration/lambda-integration/src/handler.js
> fix: lambda integration returning object with body

- src/lambda/handler-runner/in-process-runner/InProcessRunner.js
- Fixes https://github.com/dherault/serverless-offline/issues/1541
- First attempt at #1543 did not work b/c logs from the worker thread do not go to the console
- alternative considered was to add log here, but the error has been swallowed already at that point, so that won't work either: https://github.com/dherault/serverless-offline/blob/0f6c9f40ab94df8e1743ff7f4e3521abd9084f0b/src/lambda/handler-runner/worker-thread-runner/WorkerThreadRunner.js#L40-L43
- Cleanest way to solve this appears to be just removing try/catch (what this PR proposes), so root error gets logged here: https://github.com/dherault/serverless-offline/blob/0f6c9f40ab94df8e1743ff7f4e3521abd9084f0b/src/events/http/HttpServer.js#L615-L619
- `npm run lint` passes locally
- `npm run test:unit` - cannot get this to work …
> fix: Log uncaught exceptions in worker thread handlers

- README.md
- src/config/commandOptions.js
- src/config/defaultOptions.js
- src/events/http/HttpServer.js
this PR removes the `--printOuput` flag. this can be easily accomplished by just using `console.log` in your own lambda code, or by just reading the http status code and the response body in a REST client. it's less code and one option less to maintain.
**BREAKING**, next major release, v10
> fix!: remove print output option

- src/events/websocket/HttpServer.js
Add support for secure web sockets by using the TLS options when creating a server for the websockets.
When adding the httpsProtocol configuration in the serverless.yml file
```
custom:
serverless-offline:
httpsProtocol: "dev-certs"
```
serverless-offline will show the endpoints as https://localhost:3000/{default*} for HTTP and wss://localhost:3001 for WebSockets, as opposed to http:// and ws://
While https works with the certificates, the websocket protocol is not upgraded and uses http rather than https
To test:
* Add a key and a certificate in dev-certs/key.pem and dev-certs/cert.pem respectively.
* Add websocket events to the serverless.yml file
* Enable https in serverless.yml to point to the dev-certs folder
* Connect to the websocket with `wscat -c wss://localhost:3001`
wscat will …
> feat: secure web sockets

- src/events/http/HttpServer.js
A recent change prevented the default generated API key from working: https://github.com/dherault/serverless-offline/pull/1585/files#diff-c2aeb87128097ca7cd2056b14fba597e31a08404b3bedd046fb550ca602147a3L925
Fix a bug that was recently introduced and shipped in v11
I've tested this fix locally. This probably should have been covered by a unit test to prevent this from breaking originally. I can add some better tests if that's desired. I figure you probably want to ship a patch release with this fix soon though.
N/A
> fix: checking generated api key

- package-lock.json
- package.json
- src/lambda/handler-runner/docker-runner/DockerContainer.js
This PR prevents overwriting `host.docker.internal` host in WSL environment.
I added [is-wsl](https://github.com/sindresorhus/is-wsl) for checking if the process is running inside WSL.
In WSL, it seems that the host is not reachable with the gateway ip adress of `bridge` network.
For this reason, [`--add-host host.docker.internal:${gatewayIp}`](https://github.com/dherault/serverless-offline/blob/6485b017c6a5f2a1e1275b0e0642de4486c807ac/src/lambda/handler-runner/docker-runner/DockerContainer.js#L156) does not work as expected.
Docker for Windows supports `host.docker.internal` natively, so just avoid adding `host.docker.internal` and it works.
This has been tested by running [accessHost.test.js](https://github.com/dherault/serverless-offline/blob/6485b017c6a5f2a1e1275b0e0642de4486c807ac/tes …
> fix: prevent overwriting host.docker.internal in wsl

- src/events/http/createAuthScheme.js
- tests/integration/request-authorizer/request-authorizer.test.js
- tests/integration/request-authorizer/serverless.yml
- tests/integration/request-authorizer/src/authorizer.js
This PR adds support for request authorizers to look at a querystring for the identity source. With Serverless only supporting header, this adds one of the other identity sources that AWS supports. 
[This PR https://github.com/dherault/serverless-offline/pull/1600](https://github.com/dherault/serverless-offline/pull/1600) was a fantastic addition, eliminating the need for any custom local authorizer workarounds. I'm using serverless on a current project, and it's great to remove the workaround. I have a use case where I have authorizers using the header, but I also have one that requires querystring. AWS supports 4 different identity sources per their [documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html#Identity_sources). Ideally, …
> feat: Add support for request authorizers to have a querystring identity source

- src/config/supportedRuntimes.js
Added Node 18 runtime.
Closes #1615 
[AWS now supports Node 18.](https://docs.aws.amazon.com/lambda/latest/dg/lambda-nodejs.html)
> feat: Add support for nodejs18.x runtime

- src/events/http/createAuthScheme.js
- tests/integration/request-authorizer/request-authorizer.test.js
According to the official [Amazon docs](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-authorizers.html), whenever you set a request authorizer with a specific identity source, such as `$request.header.Authorization`, and a request comes WITHOUT this identity source, then API Gateway responds with a 401 Unauthorized error.
Currently, when doing a request to a function that has an Authorizer attached to it, if the identitySource is not present on the request, then serverless-offline responds with an error 500. I've made the change so it returns a 401 instead.
The `request-authorizers` suite of tests have been updated with a new test case per `describe` block (this change applies to payload format 1.0, 2.0 with simple response, with headers/query params). 
We …
> feat: request authorizers with null identitySource should return 401

- examples/events/alb/.npmrc
- examples/events/alb/handler.js
- examples/events/alb/package-lock.json
- examples/events/alb/package.json
- examples/events/alb/serverless.yml
- src/ServerlessOffline.js
- src/config/commandOptions.js
- src/config/defaultOptions.js
- src/events/alb/Alb.js
- src/events/alb/AlbEventDefinition.js
- src/events/alb/HttpServer.js
- src/events/alb/index.js
- src/events/alb/lambda-events/LambdaAlbRequestEvent.js
- src/events/alb/lambda-events/index.js
- src/utils/generateHapiPath.js
- src/utils/index.js
- tests/integration/alb-handler/handlerPayload.test.js
- tests/integration/alb-handler/serverless.yml
- tests/integration/alb-handler/src/handler.js
- tests/integration/alb-handler/src/package.json
AWS ALB support lambdas, serverless supports them as well. As such, supporting them in serverless-offline seems logical.
Based on:
- https://github.com/dherault/serverless-offline/pull/1250 by @bayoumymac
- https://github.com/tmaslen/serverless-local-alb-example by @tmaslen
Support for this has been requested by several people.
This would close #598 (which is already closed, but the feature is not supported).
It's tested on our own project with success.
I was unable to get the testsuite to run at this time, but wanted to open the PR for feedback regardless.
> feat: add support for ALB 

- src/events/alb/HttpServer.js
- src/events/http/HttpServer.js
- src/lambda/LambdaFunction.js
`serverless-offline` returns wrong status code when timeout occurs. Instead of `502`, it should return `504`.
This pull request fixes this issue.
According to serverless docs, it should be `504`.
https://github.com/serverless/serverless/blob/main/test/integration/aws/api-gateway.test.js#L226
At the moment I have tested against our own project which already specified a lambda.
The majority of the code has been untouched so it should work.
> fix: Lambda timeout status code

- package-lock.json
- package.json
Fixes a security vulnerability issue caused by `fast-xml-parser` deprecated version by upgrading `aws-sdk/client-lambda` that is using it as a dependency
Fixes [#1701](https://github.com/dherault/serverless-offline/issues/1701)
- Tested locally in my project
> Upgrade aws-sdk/client-lambda

- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/package-lock.json
- tests/scenario/lambda-frameworks/apollo-federation-supergraph/app/package.json
- tests/scenario/lambda-frameworks/apollo-server-integrations/app/package-lock.json
- tests/scenario/lambda-frameworks/apollo-server-integrations/app/package.json
This PR bumps `apollo-federation-supergraph` and `apollo-server-integrations` dependencies.
The latest two pushes to `master` has failed.
It is needed to fix the tests to create a new release of this library.
The npm test in Github actions ran successfully after the changes.
N/A
> Bump Apollo deps

- src/lambda/routes/invocations/InvocationsController.js
There is a tiny typo in one of the `InvocationsController` error messages (an `s` at the end of the word `exist`)
Quality of the plugin.
> fix(InvocationsController): typo in error message

- src/events/http/HttpServer.js
- src/events/http/createAuthScheme.js
- tests/integration/no-identity-source-authorizer/no-identity-source-authorizer.test.js
- tests/integration/no-identity-source-authorizer/serverless.yml
- tests/integration/no-identity-source-authorizer/src/authorizer.js
- tests/integration/no-identity-source-authorizer/src/handler.js
- tests/integration/no-identity-source-authorizer/src/package.json
fix #1638
If the authorizer type is REQUEST and its caching is disabled, the identity source is not required.
See #1638 for details.
I added `no-identity-source-authorizer` integration test.
> fix: support authorizer with no identity source specified

- README.md
This PR fixes the description for enabling custom authentication providers in serverless.yml files. In addition to using the correct keys, I added an usage example and direct linked the referenced integration test example.
Related to #1311
The documentation was wrong and hard to follow. Correct solution was pointed out in https://github.com/dherault/serverless-offline/issues/1311#issuecomment-1176860248 by @rion18.
Implemented the custom provider in my own project. Additionally I tested that the key `serverless-offline` and `authenticationProvider` mentioned in the README are no-ops and that the implementation in https://github.com/dherault/serverless-offline/tree/master/tests/integration/custom-authentication is in fact correct.
> doc: Fix customAuthenticationProvider documentation

- src/events/http/createAuthScheme.js
- tests/integration/restApi-authorizers/restApi-authorizers.test.js
- tests/integration/restApi-authorizers/serverless.yml
- tests/integration/restApi-authorizers/src/handler.js
- tests/integration/restApi-authorizers/src/package.json
From https://github.com/dherault/serverless-offline/issues/1674
According to [the REST API docs](https://www.serverless.com/framework/docs/providers/aws/events/apigateway):
> In this case, your identitySource could contain multiple entries for your policy cache.
Currently on startup `createAuthScheme()` only allows for one header when validating the `identitySource` entry.
This is preventing us from running serverless offline with our production configuration of using multiple headers to cache auth.
Tested locally and added integration tests.
> feat: Adding handling for multiple identitySource headers in the REST API.

- src/events/http/lambda-events/LambdaProxyIntegrationEventV2.js
- tests/integration/custom-authentication/authenticationCustomVariable.test.js
The `LambdaProxyIntegrationEventV2` does not return custom authorizer contexts in the correct format. Currently, any context data is returned directly within the `authorizer` object:
```json
{
"requestContext": {
"authorizer": {
"foo": "bar"
}
}
}
```
Instead of being nested in the `lambda` object:
```json
{
"requestContext": {
"authorizer": {
"lambda": {
"foo": "bar"
}
}
}
}
```
This change is required as it breaks the local implementation of the custom authorizer.
> fix: LambdaProxyIntegrationEventV2 authorizer context

- examples/golang-lambda/functions/ping.go
- examples/golang-lambda/go.mod
- examples/golang-lambda/go.sum
- examples/golang-lambda/package-lock.json
- examples/golang-lambda/package.json
- examples/golang-lambda/serverless.yml
- examples/golang-workspace-lambda/api/ping/go.mod
- examples/golang-workspace-lambda/api/ping/go.sum
- examples/golang-workspace-lambda/api/ping/main.go
- examples/golang-workspace-lambda/go.work
- examples/golang-workspace-lambda/go.work.sum
- examples/golang-workspace-lambda/package-lock.json
- examples/golang-workspace-lambda/package.json
- examples/golang-workspace-lambda/serverless.yml
- src/lambda/handler-runner/go-runner/GoRunner.js
This PR adds support for golang workspaces.
Without these changes, the golang runner, only worked in cases where the entire application was within a module.
This then allows us to use workspaces as well without major modifications.
I have added two examples to show the case where go is integrated using a module or using a workspace.
> feat: Add support for golang workspace

- src/config/supportedRuntimes.js
Added Node 18 runtime.
Closes https://github.com/dherault/serverless-offline/issues/1742
[AWS now supports Node 18.](https://docs.aws.amazon.com/lambda/latest/dg/lambda-nodejs.html)
https://aws.amazon.com/blogs/compute/node-js-20-x-runtime-now-available-in-aws-lambda/
related PR in serverless framework
https://github.com/serverless/serverless/pull/12251
> Add support for nodejs20.x runtime

- README.md
This PR updates the DynamoDB component in our project, transitioning from `serverless-dynamodb-local` to `serverless-dynamodb`. The primary motivation for this change is the lack of maintenance and critical issues with `serverless-dynamodb-local`, which prevent the local installation of DynamoDB. A significant issue is the change in the URL from which DynamoDB is downloaded, a change not accommodated by `serverless-dynamodb-local`, rendering it unusable.
`serverless-dynamodb` is a direct fork which is maintained and solves above problem.
Modified the README file to reference serverless-dynamodb instead of serverless-dynamodb-local
> docs: change to serverless-dynamodb

- src/utils/__tests__/getApiKeysValues.test.js
- src/utils/getApiKeysValues.js
Fixes the problem where `getApiKeysValues` would only allow `FIRST_API_KEY` in the following config, and not `SECOND_API_KEY` because it's not an object.
```yaml
provider:
name: aws
apiGateway:
apiKeys:
- name: FIRST_API_KEY_NAME
value: FIRST_API_KEY
- SECOND_API_KEY
```
Strings are supported, according to the serverless (docs)[https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml#api-gateway-v1-rest-api].
- Allows using standard serverless syntax
Fixes https://github.com/dherault/serverless-offline/issues/1661
Tested with unit tests with both types of input
> fix: Allow string values in provider.apiGateway.apiKeys

- src/events/http/createAuthScheme.js
Prior to https://github.com/dherault/serverless-offline/pull/1600 change, APIGatewayEvent.requestContext object available in custom authorizer lambda had accountId and apiId fields. We used these fields construct methodArn inside our authorizer lambda. But the above change deleted these fields. Any reason why the fields are removed? AWS Lambda https://github.com/types still refer to [these fields](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b1531302ae0883690b6424400d7b9e9295c6277f/types/aws-lambda/common/api-gateway.d.ts#L23).
Fixed: #1635
> fix: Custom Authorizer Lambda Request context missing accountId and apiId fields

- src/events/http/HttpServer.js
- tests/integration/request-authorizer/request-authorizer.test.js
- tests/integration/request-authorizer/serverless.yml
- tests/integration/request-authorizer/src/handler.js
AWS API Gateway does not include the `event.requestContext.authorizer` field if there is no `authorizer` configured for the function.
This PR deletes the `event.requestContext.authorizer` field if the function does not have an authorizer.
- I'm doing serialization of API Gateway in Golang
- It was failing because the `authorizer` payload didn't match what it expected
- Upon further investigation, I found that `serverless-offline` was _always_ setting `event.requestContext.authorizer` if a `Bearer` token comes through in the HTTP Authorization headers.
- My solution is to simply remove `event.requestContext.authorizer` if the lambda function does not have an `authorizer` set.
I've written tests and included them in this PR. Please let me know if you want me to kick the tires in any other …
> fix: skip adding authorizer to event if no authorizer is configured

- src/config/supportedRuntimes.js
- tests/integration/docker/provided-al2023/bootstrap
- tests/integration/docker/provided-al2023/dockerProvided.test.js
- tests/integration/docker/provided-al2023/handler.sh
- tests/integration/docker/provided-al2023/serverless.yml
This PR adds support for provided.al2023 (https://docs.aws.amazon.com/linux/al2023/ug/lambda.html)
AL2023 image is available for some time ans should be added. `provided.al2023` runtime is based on the AL2023 minimal container image, it is substantially smaller at less than 40 MB than the `provided.al2` runtime at around 109 MB
New tests has been added for provided.al2023
> feat: add support for provided.al2023

- examples/events/alb/serverless.yml
- examples/events/alb/src/handler-response-header.js
- src/events/alb/HttpServer.js
- tests/integration/alb-headers/alb-headers.test.js
- tests/integration/alb-headers/serverless.yml
- tests/integration/alb-headers/src/handler.js
- tests/integration/alb-headers/src/package.json
This PR adds support for ALB Event handlers to return headers.
This enables different "Content-Type" or "Set-Cookie" headers.
Fixes #1728 
Examples were added to manually test as well as integration tests added.
> fix: Support ALB Event response headers

- src/events/http/HttpServer.js
- tests/integration/request-authorizer/request-authorizer.test.js
- tests/integration/request-authorizer/serverless.yml
httpApi authorizer's have their config in the provider section with a name that can be used by httpApi events to attach that authorizer.  The authorizer's underlying function is separately defined and is allowed to have a different name than the authorizer config in the provider section.  The current implementation by serverless-offline requires that both of those names are the same.  This PR fixes this issue by embedding all of the provider config and setting the function name to the one defined in the config.
Fixes #1624 
Manually tested with a small sample app that reproduced the initial issue.  Updated existing integration tests that weren't actually using the correct authorizer names (they were using the function names).  Added new integration test to reference an authorizer based on …
> fix: Support httpApi authorizer with different config and function names

- src/events/http/HttpServer.js
- src/events/http/createJWTAuthScheme.js
- src/events/http/lambda-events/LambdaProxyIntegrationEvent.js
- src/events/http/lambda-events/LambdaProxyIntegrationEventV2.js
- tests/integration/jwt-authorizer/jwt-authorizer.test.js
- tests/integration/jwt-authorizer/serverless.yml
Need to work locally with an Okta dev JWT instead of cognito. There was only one key difference that had to be implemented.
Local httpApi JWT validation was written around Cognito but would not work with a dev JWT token from Okta. The only key difference is scopes provided as an scp array instead of a scopes text string, so the changes were just related to that. It will use the scp array if provided, but falls back to original behavior otherwise.
In unit tests, I did put in a new authorizer in the serverless.yml also reflecting the different audience and a JWT Okta example showing some other differences like cid vs client_id but the authorizer already handles those differences.
Tested with dev key on my own project using serverless-offline pointing to file:// per docs from my original …
> feat: support dev Okta JWT tokens

- src/events/authMatchPolicyResource.js
- tests/old-unit/authMatchPolicyResource.test.js
This changes the regexp used to test resource arns with wildcards so that they don't have an implicit wildcard at the end
Resolves #1191
I have run the tests and used this locally
> fix: ensure resource policy matches the whole arn

- src/events/authMatchPolicyResource.js
- tests/old-unit/authMatchPolicyResource.test.js
Improves the parsing logic of resource arns in authorizer policies so that it handles wildcards more correctly
Currently `serverless-offline` will crash if you use a resource arn that ends with a wildcard'd segment even though that is allowed [per the docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-control-access-using-iam-policies-to-invoke-api.html#api-gateway-calling-api-permissions):
> If you specify a wildcard (*), the Resource expression applies the wildcard to the rest of the expression.
and [here too](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_resource.html#reference_policies_elements_resource_wildcards):
> If the wildcard (*) is the last character of a resource ARN segment, it can expand to match beyond colon …
> fix: improve wildcard handling in authorizer policy resource parser

- src/events/http/createAuthScheme.js
As per, https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html#http-api-lambda-authorizer.payload-format Events with payload version 2.0 for HTTP APIs include path parameters and query string parameters
Sometimes, path parameters need to be used in an authorizer
Yes, locally. Changes are trivial.
> Add pathParameters and queryStringParameters to payload version 2.0

- src/lambda/handler-runner/python-runner/invoke.py
Add support of base64 encoded binary response from aws python lambda function
API Gateway will treat lambda-proxy responses with isBase64Encoded set  
to true as binary as long as the mime-type matches one of the allowed  binary types.
We need Python lambdas to support base64 handling. At this point serverless-offline contains Base64 handling for JavaScript lambdas only.
> Python handle base64 encoded binary response from aws lambda function

- src/events/http/HttpServer.js
- src/lambda/handler-runner/python-runner/PythonRunner.js
- tests/runtimes/python/python3/handler.py
- tests/runtimes/python/python3/python3.test.js
- tests/runtimes/python/python3/serverless.yml
Return a 500 Internal Server Error when the Python handler raises an error
When (Python) code raises an error, AWS Lambda returns a 500 with a generic JSON response.
With this change the behaviour of Serverless Offline is more inline with AWS Lambda.
Added an automated test for Python.
> fix: return 500 Internal Server Error on python error

- src/lambda/handler-runner/python-runner/invoke.py
In this scenario, we are expecting a body key in the result object, but what if the result doesn't have a body key or if the result is a simple boolean? I actually, encountered a situation where a Lambda function was returning a bool, which caused the Lambda function to crash, leading to timeouts.
To address this, I added exception handling. If the result object contains a body key, it will function as expected. However, if the body key is absent, the Lambda function won't crash, preventing timeouts.
This will resolve the issue where, if the result object doesn't have a body key, or if the result is a string or boolean, it won't crash. The exception will be handled smoothly.
I have added this change to the invoke.py and then ran the same lambda function, which resolved the issue and I was …
> handle result structure without body

- src/events/http/HttpServer.js
- src/lambda/handler-runner/python-runner/PythonRunner.js
- tests/runtimes/python/python3/handler.py
- tests/runtimes/python/python3/python3.test.js
- tests/runtimes/python/python3/serverless.yml
Reverts dherault/serverless-offline#1796
> Revert "fix: return 500 Internal Server Error on python error"

- package-lock.json
- package.json
First of all thx for all the great work. Like many others we use `serverless-offline` at work. Today we got a dependabot alert for `serverless-offline` because it's dependency package `jsonpath-plus` is subject to a security vulnerability. [A recent bump](https://github.com/dherault/serverless-offline/issues/1825) to Version 10.0.0 only temporarily helped as it was soon found out to still be vulnerable to RCE. 
**Bumped `jsonpath-plus` dependency from 10.0.0 to 10.1.0 to get on top of a security vulnerability with the possibility of remote code execution.** 
For reference you can check out the snyk report via NVD [here](https://nvd.nist.gov/vuln/detail/cve-2024-21534) or see the issue from `jsonpath-plus` [here](https://github.com/JSONPath-Plus/JSONPath/issues/226).
> fix: update dependency to close vulnerability

- src/config/supportedRuntimes.js
- tests/integration/docker/multiple/serverless.yml
- tests/integration/docker/nodejs/nodejs22.x/dockerNodejs22.x.test.js
- tests/integration/docker/nodejs/nodejs22.x/handler.js
- tests/integration/docker/nodejs/nodejs22.x/serverless.yml
Add support for Node.js 22 runtime to v13 branch
Same changes as https://github.com/dherault/serverless-offline/pull/1837 but for v13
> feat: add support for nodejs22.x runtime to v13

- package-lock.json
- package.json
This PR addresses jsonpath-plus vulnerability mentioned here https://github.com/dherault/serverless-offline/issues/1825. This was already addressed in the main branch here https://github.com/dherault/serverless-offline/pull/1835.
For reference you can check out the Snyk report via NVD [here](https://nvd.nist.gov/vuln/detail/cve-2024-21534).
Based on https://github.com/JSONPath-Plus/JSONPath/issues/226, the vulnerability is patched in v10.2.0.
> fix: update v13 to close jsonpath vulnerability

- src/config/supportedRuntimes.js
Add support for Python 3.12 and 3.12 to v13 version
Python 3.12 is supported by v14 but not by v13.
There is a warning, coming probably from serverless, but nevertheless I can work with Python 3.12 using this fork
```
❯ serverless offline
Running "serverless" from node_modules
Warning: Invalid configuration encountered
at 'provider.runtime': must be equal to one of the allowed values [dotnet6, go1.x, java17, java11, java8, java8.al2, nodejs14.x, nodejs16.x, nodejs18.x, nodejs20.x, provided, provided.al2, provided.al2023, python3.7, python3.8, python3.9, python3.10, python3.11, ruby2.7, ruby3.2]
Learn more about configuration validation here: http://slss.io/configuration-validation
Starting Offline at stage dev (<some-aws-region>)
Offline [http for lambda] listening on …
```
> feat: add support for python 3.12 and 3.13 to v13

- src/lambda/handler-runner/in-process-runner/aws-lambda-ric/UserFunction.js
- tests/handler-module-formats/commonjs/handlerModuleFormats.test.js
- tests/handler-module-formats/module/handlerModuleFormats.test.js
- tests/handler-module-formats/module/serverless.yml
- tests/handler-module-formats/module/ts-extension-load-esm/.gitignore
- tests/handler-module-formats/module/ts-extension-load-esm/handler.ts
- tests/handler-module-formats/module/ts-extension-load-esm/node_modules/testpackage/index.js
- tests/handler-module-formats/module/ts-extension-load-esm/node_modules/testpackage/package.json
- tests/handler-module-formats/module/ts-extension-load-esm/package.json
Closes #1848 
See #1848
Tested on a service locally that failed previously. See #1848 for environment details.
N/A
> Load TypeScript in ESM mode if package.json type is module

- src/lambda/LambdaFunction.js
- src/utils/__tests__/renderIntrinsicFunction.test.js
- src/utils/renderIntrinsicFunction.js
- Support CloudFormation the following intrinsic functions in environment variable
- `Fn::Join`
- `!Join`
- `Fn::Sub`
- `!Sub`
- Fix #1013
- Fix #1713
example yaml:
```yaml
service: aws-node-project
frameworkVersion: '3'
provider:
name: aws
runtime: nodejs18.x
region: ap-northeast-1
stage: dev
environment:
getKeyARN:
Fn::Join:
- ':'
- - 'arn:aws:lambda'
- ${self:provider.region}
- Ref: 'AWS::AccountId'
- 'function'
- ${self:service}-${self:provider.stage}-getKey
qa: 12345
functions:
function1:
handler: index.handler
environment:
getKeyARN:
Fn::Join:
- ':'
- - 'arn:aws:lambda'
- ${self:provider.region}
- Ref: 'AWS::AccountId'
- 'function'
- ${self:service}-${self:provider.stage}-getKey
qa: 12345
plugins:
- serverless-offline
```
eample js:
```js
module.exports.handler = async (event) => { …
```
> feat: Support CloudFormation Join & Sub function in environment variable
